### ISSUE TITLE
Potential performance issue in stores in the Chat demo

### ISSUE THREAD

**Issue by tiye** [facebook/flux#100]
I'm looking solutions for our single page app built with React and Backbone. And in Backbone, a view listens to its own Model or Collection. So given a View of message, it does not refresh when a message of another room updates.

While in React it appears maintaining Stores like Models is quite a bad idea. In the Chat demo, there is only one MessageStore here.
https://github.com/facebook/flux/tree/master/examples/flux-chat/js/stores
Suppose someone is chatting in room A, updates of room B may trigger a View refresh. When there are hundreds of messages, we may face a issue of performance.

So I quite like to know what's your concern when you wrote the Chat demo, how about that it performance when it gets large?

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
