### ISSUE TITLE
Publish 2.0.2 to npm

### ISSUE THREAD

**Issue by ryanzec** [facebook/flux#101]
It look like the latest version on NPM is 2.0.1 so 2.0.2 should probably be pushed to npm.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyldvs** [comment]
bumped things to 2.1.1 now
