### ISSUE TITLE
Example component unit tests

### ISSUE THREAD

**Issue by bradrydzewski** [facebook/flux#103]
It would be great to see some example unit tests for components and mocking the stores.

**Comment by ericmasiello** [comment]
Also related, when cd to examples/flux-todomvc and run "npm test" I see it starts up Jest but it just hangs without running any of the actual tests. What gives?

**Comment by zpao** [comment]
Jest has issues when running in node / iojs > 0.10, could be that.

**Comment by jerryf196** [comment]
I am following the unit test for TotoStores.js. Writing up my own unit test according to this file
https://github.com/facebook/flux/blob/master/examples/flux-todomvc/js/stores/__tests__/TodoStore-test.js

It fails on this line:
callback = AppDispatcher.register.mock.calls[0][0];

Unit tests error output:
TypeError: Cannot read property '0' of undefined.

Here is my sample code
http://pastebin.com/GGB3ZVMy

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sahas-** [comment]
I'm down with this issue as well. Looks like callback is not registered with the dispatcher.
AppDispatcher.register.mock returns { calls: [], instances: [] }. 
Everything is mocked except mystore and object-assign.

Node: v4.2.2
Jest: v0.8.0

Not sure if this is fixed and closed.. is there a workaround?

**Comment by everystone** [comment]
Any updates on this? I can't get the examples to run.
TypeError: Cannot read property '0' of undefined on callback = AppDispatcher.register.mock.calls[0][0];

**Comment by miguelmota** [comment]
Having same issue

**Comment by salmankhann** [comment]
i'm having the same issue. Any updates on this?

**Comment by HusseinElsayed** [comment]
I'm having something similar to this one 
TypeError: Cannot read property 'calls' of undefined
any idea how to pass this error ?
