### ISSUE TITLE
publish /dist in npm package...

### ISSUE THREAD

**Issue by busticated** [facebook/flux#104]
like react does here --> https://github.com/facebook/react/blob/master/npm-react/package.json

this way people can access the [`dist` files](https://github.com/facebook/flux/tree/master/dist) using a module loader of their choice

**Comment by rakeshok** [comment]
+1

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by prabirshrestha** [comment]
any updates on this?

**Comment by zpao** [comment]
Heh, @kyldvs just pushed 2.1 but we didn't do this. Perhaps we could push a quick 2.1.1 with it?

**Comment by kyldvs** [comment]
Whoops.. anyway should be in 2.1.1, just did another quick push.
