### ISSUE TITLE
Docs on dispatcher is outdated (or just wrong)

### ISSUE THREAD

**Issue by robrobbins** [facebook/flux#107]
Just noticed that the documentation located [here] (http://facebook.github.io/flux/docs/overview.html#what-about-that-dispatcher) states that a call to `...waitFor(...)` takes a second `argument`, a callback. [I am pretty sure that is not correct](https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L154).

**Comment by fisherwebdev** [comment]
The [Flux overview page](http://facebook.github.io/flux/docs/overview.html) has been updated.  Among other changes, it now accurately reflects the API of the FB [dispatcher](https://www.npmjs.com/package/flux) available on npm.
