### ISSUE TITLE
Server/view action dispatch methods

### ISSUE THREAD

**Issue by RileyTomasek** [facebook/flux#119]
Why do server and view actions have separate dispatch methods in the examples, without ever providing any inherent value. It seems like this could easily be done by just passing an extra property on the action instead. Am I missing something here or should this separation be removed?

**Comment by RileyTomasek** [comment]
@fisherwebdev I will try to get to it tomorrow. It should be pretty fast.

Did you see my PR that was also for the chat example? (#120)

**Comment by tleunen** [comment]
I thought it was separate because you could use the same action both for view and server event, and do something different in both cases.
But for sure it didn't make sense to have it in the todo example as there is no server api.

**Comment by fisherwebdev** [comment]
@tleunen If you need to use the same action, you can just add a property to the action denoting the origin and use that as a flag in the stores to handle the action differently.

**Comment by fisherwebdev** [comment]
This was taken care of in #172 by @jarsbe.
