### ISSUE TITLE
Question: Why remove the AppDispatcher.handleAction

### ISSUE THREAD

**Issue by joeyhipolito** [facebook/flux#123]
Why remove the AppDispatcher.handleAction, was it because it isn't need in TodoApp example? Or it is entirely not needed in most applications? Or we need it in some real life use cases because:

> We also add a handleAction helper method to our Dispatcher instance, so that we can identify where this action came from. -- [scotch.io tut](https://scotch.io/tutorials/creating-a-simple-shopping-cart-with-react-js-and-flux#dispatcher)

**Comment by fisherwebdev** [comment]
The handleServerAction and handleViewAction wrappers around Dispatcher.dispatcher were unnecessary cruft that came over from a couple of applications we built at Facebook.  If one needs to determine whether a particular action came from the server or the view, a property can be added to the action to denote the origin.

It's a bit cleaner to have the dispatcher's payload be synonymous with the action.

**Comment by developer94404** [comment]
For those wondering what the above means: just replace 'dispatcher.handleAction()' calls with 'dispatcher.dispatch()' and it will work.
