### ISSUE TITLE
Clarify Dispatcher docs in docs/Dispatcher.md and in Dispatcher.js

### ISSUE THREAD

**Issue by fisherwebdev** [facebook/flux#126]
Audit and revise:
https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L20-L110

In particular:

Use of "chained" is not clear -- the docs mean to say that a chain of dependencies may be declared across multiple stores.
https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L89

There might also be something strange going on with the multiple cases, as revised in #7 and this is worth examining again.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
