### ISSUE TITLE
How does Ajax fit into Flux

### ISSUE THREAD

**Issue by jiyinyiyong** [facebook/flux#127]
It's common case that we send ajax to server when there is an action sent to store. But is not detailed in Flux's docs http://facebook.github.io/flux/docs/overview.html
While there's a diagram implicating that Web APIs are called inside Actions. So is ajax called inside Actions? If it is, how does it solve such a case:
* user clicks button
* fetch messages
* show loading after the button
* messages back
* hide loading button
* display messages 
![](https://cloud.githubusercontent.com/assets/1869/5191535/08692222-74a4-11e4-8482-d7557117b23e.png)

**Comment by sompylasar** [comment]
Related question: #122

**Comment by tracker1** [comment]
Store calls backing service, callback from service raised change event, which then passes through to react-views... Think of the store also having a client interface to where the data is... in the case of a REST/Ajax Service, this is where the client-server communication happens.

**Comment by jiyinyiyong** [comment]
Didn't notice updates in the examples, perfering that file as the anwser:
https://github.com/facebook/flux/blob/master/examples/flux-chat/js/utils/ChatWebAPIUtils.js
