### ISSUE TITLE
Suggestion: Move `testing flux` to here and make more of it.

### ISSUE THREAD

**Issue by robrobbins** [facebook/flux#132]
just a recommendation. I have a growing number of TDD type specs in a current large project and would be fine contributing if needed.

also they should be correct ;) The instructions for getting the ref to the mocked register at http://facebook.github.io/react/blog/2014/09/24/testing-flux-applications.html#testing-stores do not work for me...

**Comment by fisherwebdev** [comment]
The Flux testing blog post was already added to the Flux documents in 1eb5fb13.

Also, the tests in the example application pass.  Maybe you can follow the example tests to see what the problem might be in your tests.  If there is an actual problem in the documentation, please reopen this issue.
