### ISSUE TITLE
Creating a Gitter room for React/Flux 

### ISSUE THREAD

**Issue by joshbedo** [facebook/flux#135]
Switching from Marionette over to React/Flux i'm now wishing their becomes a [Gitter](https://gitter.im/dev-ua/reactjs) chatroom for React/Flux :)

Reasons I think it's a great idea
- You can ask questions to the community and easily get answers from others and core contributors
- You get to see how other users are taking advantage of Actions, Dispatchers, Stores, Getters, etc.
- It's an awesome way to share other design patterns and cool projects surrounding flux like [NuclearJS](https://github.com/optimizely/nuclear-js), [ImmutableJS](https://github.com/facebook/immutable-js), [VueJS](http://vuejs.org/) and [RiotJS](https://muut.com/riotjs/)
- You can see all of the issues/PRs being actively opened within the repo

Hopefully that's convincing enough to start one :)

**Comment by volkanunsal** [comment]
You can ask questions and talk to others about Flux with Github issues too. Case in point, this issue.

**Comment by joshbedo** [comment]
Look how active this room is for example, you can't achieve the same thing with github issues. Otherwise I wouldn't create an issue :)
[https://gitter.im/marionettejs/backbone.marionette](https://gitter.im/marionettejs/backbone.marionette)

**Comment by andreypopp** [comment]
There's #reactjs channel at irc.freenode.net which is active (around 400 members).

**Comment by fisherwebdev** [comment]
The main place for chat right now is the reactjs channel on freenode IRC.  

Lots of Facebook employees hang out there who have extensive experience with Flux.  Many have been working with Flux for about two years, and a few even a bit longer than that.

That said, I'm open to the idea of creating a Gitter chatroom.  I am seeing some concerns on the web about their request for extended permissions, however, which might be a deal breaker for me.  I will do some research on it.

**Comment by PaulLeCam** [comment]
If you want more information about the permissions: https://gitter.zendesk.com/hc/en-us/articles/200176672-Authenticating-with-GitHub

**Comment by chicoxyzzy** [comment]
there is also Slack chat http://www.slackchats.com/site/contents/content/43043/2014-12-24/flux-reactjs-chat

**Comment by joshbedo** [comment]
Awesome thanks for sharing I guess those are sufficient enough, I'll close this.

**Comment by chicoxyzzy** [comment]
also you can get invite to react + flux slack chat here http://reactiflux.com/
