### ISSUE TITLE
Cannot install on Mavericks

### ISSUE THREAD

**Issue by matobago** [facebook/flux#148]
npm WARN package.json jsxc@0.1.6 No repository field.
npm WARN prefer global jsxc@0.1.6 should be installed with -g
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.3.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package envify does not satisfy its siblings' peerDependencies requirements!

npm ERR! Please include the following file with any support request:
npm ERR!    /react-boilerplate/npm-debug.log

**Comment by fisherwebdev** [comment]
I'm running Mavericks, as are most people that have gotten this running.  This is a problem with how something related to node or npm or node_modules is installed (or not) on your machine, not Mavericks.
