### ISSUE TITLE
npm install fails on flux todo mvc

### ISSUE THREAD

**Issue by jkatsnelson** [facebook/flux#157]
$ npm install
npm WARN package.json jsxc@0.1.6 No repository field.
npm WARN prefer global jsxc@0.1.6 should be installed with -g
npm ERR! peerinvalid The package envify does not satisfy its siblings' peerDependencies requirements!

npm ERR! System Darwin 14.1.0
npm ERR! command "/usr/local/opt/nvm/v0.10.28/bin/node" "/usr/local/opt/nvm/v0.10.28/bin/npm" "install"
npm ERR! cwd /Users/kats/Code/react-boilerplate
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/kats/Code/react-boilerplate/npm-debug.log
npm ERR! not ok code 0

**Comment by rstawarz** [comment]
Was there a solution to this?

**Comment by jkatsnelson** [comment]
I think I had to blow away my node_modules and it worked

**Comment by grantgeorge** [comment]
@rstawarz try

```
rm -r node_modules/

npm cache clean

npm install
```
