### ISSUE TITLE
Make "invariant" as a separated module

### ISSUE THREAD

**Issue by Kureev** [facebook/flux#159]
Dear core team,

Could you make "invariant" as a standalone dependency (or as least export it as require('flux').invariant) to allow other users use it in their code. 

For example, i'm developing library, which using your flux dispatcher as an underlying layer for my own dispatcher. So, i'd like to use your assert mechanism in my code too.

Now i'm using
```javascript
var invariant = require('flux/lib/invariant');
```
but not sure it's a best idea.

**Comment by fisherwebdev** [comment]
@zpao is working on this, but it probably won't live here.  I think eventually we will require invariant from another module.

**Comment by zertosh** [comment]
@fisherwebdev Oh I didn't know this. @zpao Let me know if you guys want to own this https://www.npmjs.com/package/invariant or if it's fine like that
