### ISSUE TITLE
Chat example flow

### ISSUE THREAD

**Issue by malte-wessel** [facebook/flux#161]
Hey guys, 

I'm trying to understand the chat example and how changes in the stores affect the listening components. When a thread is clicked, the data in both `MessageStore` and `ThreadStore` changes. Each store emits a change event and the `_onChange` method of the `MessageSection` component is called twice (because it's listening to both of them). The `_onChange` method invokes setState, which should lead the component to render two times. However, the render method is only called once, and I can't figure out why. Even if I remove the `waitFor` statement in the `MessageStore`. Any ideas?

**Comment by kharin** [comment]
Dispatcher is synchronous and `setState` only causes render on next tick, [see notes](http://facebook.github.io/react/docs/component-api.html#setstate) on `setState`.

**Comment by malte-wessel** [comment]
ahh ok that makes sense. thx!
