### ISSUE TITLE
Return a "snapshot" of the store object instead of returning a reference to the object directly

### ISSUE THREAD

**Issue by gsklee** [facebook/flux#173]
Please consider updating the docs and examples from this pattern:

```javascript
var user = {
      name: ''
    };

export default new class Store extends EventEmitter {

  ...

  get value() {
    return user;
  }

  ...

}();
```

to this pattern:

```javascript
  get value() {
    return Object.assign({}, user);
  }
```

More information [here](https://github.com/facebook/react/issues/3297).

**Comment by fisherwebdev** [comment]
Use immutable data if you are working with shouldComponentUpdate.  I'd recommend [ImmutableJS](http://facebook.github.io/immutable-js/) for that.

We are keeping these examples very simple so they are easy to understand -- the minimum code required to explain the pattern.  Use of shouldComponentUpdate fall outside of that.
