### ISSUE TITLE
npm start command results in error message

### ISSUE THREAD

**Issue by Tapjay** [facebook/flux#180]
In attempting to run the examples, I ran npm install which seemed to finish successfully (finished the 'publish' task and exited) but hit an issue when I tried npm start. I get the following output:

    npm ERR! Darwin 14.1.0
    npm ERR! argv "node" "/usr/local/bin/npm" "start"
    npm ERR! node v0.10.31
    npm ERR! npm  v2.1.17
    npm ERR! missing script: start

    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request
    npm ERR!     /Users/julian/Development/react-projects/flux/npm-debug.log

Here is a screen shot of npm-debug.log

![screen shot 2015-03-21 at 16 04 27](https://cloud.githubusercontent.com/assets/2171281/6764277/34b60552-cfe4-11e4-95c3-d46d9d0f7f13.png)

Can anyone help? Thanks a lot.

**Comment by zpao** [comment]
It's as the error says, there is no `start` script at the root. If you would like to run the examples, `cd` into the one you want to run, then `npm install` and `npm start` from there

**Comment by Tapjay** [comment]
Damn. I feel silly. Thanks a lot, I was running the commands in the home directory. Cheers.
