### ISSUE TITLE
Remove unused reference to MessageStore

### ISSUE THREAD

**Issue by twobitfool** [facebook/flux#184]
[Line 14 of ThreadSection](https://github.com/facebook/flux/blob/master/examples/flux-chat/js/components/ThreadSection.react.js#L14)

**Comment by ptz0n** [comment]
Good catch!

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mandaltapesh** [comment]
this is the grep output for string "MessageStore"
Binary file .git/index matches
examples/flux-chat/js/components/MessageSection.react.js:var MessageStore = require('../stores/MessageStore');
examples/flux-chat/js/components/MessageSection.react.js:    messages: MessageStore.getAllForCurrentThread(),
examples/flux-chat/js/components/MessageSection.react.js:    MessageStore.addChangeListener(this._onChange);
examples/flux-chat/js/components/MessageSection.react.js:    MessageStore.removeChangeListener(this._onChange);
examples/flux-chat/js/components/MessageSection.react.js:   * Event handler for 'change' events coming from the MessageStore
examples/flux-chat/js/components/ThreadSection.react.js:var MessageStore = require('../stores/MessageStore');
examples/flux-chat/js/stores/UnreadThreadStore.js:var MessageStore = require('../stores/MessageStore');
examples/flux-chat/js/stores/UnreadThreadStore.js:    MessageStore.dispatchToken
examples/flux-chat/js/stores/MessageStore.js:var MessageStore = assign({}, EventEmitter.prototype, {
examples/flux-chat/js/stores/MessageStore.js:MessageStore.dispatchToken = ChatAppDispatcher.register(function(action) {
examples/flux-chat/js/stores/MessageStore.js:      MessageStore.emitChange();
examples/flux-chat/js/stores/MessageStore.js:      MessageStore.emitChange();
examples/flux-chat/js/stores/MessageStore.js:      MessageStore.emitChange();
examples/flux-chat/js/stores/MessageStore.js:module.exports = MessageStore;

**Comment by mandaltapesh** [comment]
examples/flux-chat/js/components/ThreadSection.react.js  is the only one to be modified according to the above grep search ..it is a simple one line deletion ..opened a PR :)

**Comment by kyldvs** [comment]
Should be resolved now
