### ISSUE TITLE
How to spin up a web server in examples?

### ISSUE THREAD

**Issue by mtbvang** [facebook/flux#196]
The example doco says 'To run the app, spin up an HTTP server and visit http://localhost/.../todomvc-flux/'. As someone new to Flux I'm not sure how to do this with all the moving parts. 

Do I use the http module and http.createServer(app)? I'm not sure how this works with browsify. Would be good if the examples actually had the http server wired in.

**Comment by zpao** [comment]
The next sentence is "Or simply open the index.html file in a browser." This works for me and avoids needing to know anything about setting a server up (though we might want to just get rid of the first sentence if that works)

**Comment by hbrls** [comment]
@zpao `file://.../index.html` warns me of not installing the react debug extension which I've installed.

**Comment by mtbvang** [comment]
@zpao I got the html working on my local host machine as well. I just hit the http server issue when I ran it in a docker container with vagrant like how I normally do. I guess what I'm really looking for is a working flux boilerplate. It's understandable if the examples are to be keep to a bare minimum just to demonstrate the flux concept.
