### ISSUE TITLE
AppDispatcher.register(function(action)  not called

### ISSUE THREAD

**Issue by watsonwu9** [facebook/flux#201]
![2015-05-07 15 49 00](https://cloud.githubusercontent.com/assets/912960/7519242/6b44a88c-f512-11e4-98b1-fabf11b5be85.png)
![2015-05-07 15 49 28](https://cloud.githubusercontent.com/assets/912960/7519239/6b0f9d54-f512-11e4-8b34-fd330ef33a06.png)
![2015-05-07 15 50 24](https://cloud.githubusercontent.com/assets/912960/7519240/6b15df66-f512-11e4-8d55-62c6a009bde4.png)
![2015-05-07 15 50 39](https://cloud.githubusercontent.com/assets/912960/7519241/6b256ee0-f512-11e4-95d4-367cd2d941c2.png)

hi, i just started to use flux and encountered a very wired bug. today I tried to copy some of the code in the flux-todomvc project at https://github.com/facebook/flux/tree/master/examples/flux-todomvc 
After I dispatch my action, the AppDispatcher.register(function(action)) is NOT called. 
Can anyone tell me why?

**Comment by lili21** [comment]
code not image

**Comment by abhinavrastogi** [comment]
It seems the Flux.Dispatcher (or AppDispatcher in your case) is not a singleton by itself. Thus the two places where you require it (action and store), get different instances of Dispatcher. You need to wrap it in a custom singleton implementation.

My question: why is it not a singleton by itself? I am submitting a PR for the same.

**Comment by kyldvs** [comment]
Sounds like this is resolved, re-open if not!
