### ISSUE TITLE
Provide an explicit outline for action-response flows between dispatchers and stores

### ISSUE THREAD

**Issue by langri-sha** [facebook/flux#208]
Based on the current writings and diagrams, it's possible for developers to hastily conclude that it is strongly recommended that stores themselves are not allowed to create actions. The documentation on  [Structure and Data Flow](https://facebook.github.io/flux/docs/overview.html#structure-and-data-flow) or [Actions and the Dispatcher](https://facebook.github.io/flux/docs/actions-and-the-dispatcher.html#content) needs to be supplemented with an exemplar data flow that is not originating from client-side interactions exclusively.

Researching the discussions on the internet reveals that many developers are strongly fixated to the understanding that stores are conceptualized in a way that doesn't permit them to initiate cyclic, blow-for-blow, action-response flows together with a dispatcher, even though such communication still warrants that stores self-update in response to an action, maintaining the unidirectional flow of data within the application.

For example, please see the [comments thread](http://stackoverflow.com/a/26581808/44041) on a SO question where @fisherwebdev explains that stores are allowed to communicate with the dispatcher to generate actions that they can reciprocally use to update themselves in response to data received from a Web API request they instigated.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyldvs** [comment]
We added some more examples, and specifically the async-example has actions originating from stores. The two referenced documents have also been removed. So I believe this is no longer an issue.

New Examples: https://github.com/facebook/flux/tree/master/examples
