### ISSUE TITLE
Feature Request: Use promises to simulate real API calls

### ISSUE THREAD

**Issue by jsifalda** [facebook/flux#210]
Hey there!

I would like to see in chat app example using of promises to simulate real API call. 
To me it makes differences in flux architecture.
Eg. how flux can handle asynchronous code (in actions or stores?!) etc.

Thanks in advance!

**Comment by dpercy** [comment]
+1

**Comment by mtrenker** [comment]
if you look at the [createMessage](https://github.com/facebook/flux/blob/master/examples/flux-chat/js/utils/ChatWebAPIUtils.js#L49) method in the ChatWebAPIUtils file, there is a fake success callback simulated with a timeout. This is pretty much it.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyldvs** [comment]
Here's an example that use Flux while talking to a real server implementation: https://github.com/staltz/flux-challenge/tree/master/submissions/kyldvs
