### ISSUE TITLE
move examples to es6?

### ISSUE THREAD

**Issue by davis** [facebook/flux#212]
Was just wondering if you guys would want a PR for that

**Comment by fisherwebdev** [comment]
https://twitter.com/fisherwebdev/status/603585880255639552

Maybe, haven't decided.  Going to talk with some folks at FB about it.  Regardless, I wouldn't want one massive PR for both examples, but would need to approach it in digestible chunks.  At least two PRs, one for each example, but cutting it down further would be better.

**Comment by kyldvs** [comment]
Here is at least one example in ES6, https://github.com/facebook/flux/tree/master/examples/flux-utils-todomvc

I would support moving the others too.

**Comment by kyldvs** [comment]
We have one in ES6, I think that is okay for now.
