### ISSUE TITLE
flux-chat example: Using never defined thread.lastTimestamp in ThreadStore

### ISSUE THREAD

**Issue by xak2000** [facebook/flux#218]
In flux-chat example there is [`thread.lastTimestamp`](https://github.com/facebook/flux/blob/172a114ac89a62ee860cffa128ef959589386b50/examples/flux-chat/js/stores/ThreadStore.js#L31) variable that never defined anywhere.
I think it is just a typo. Meant to be `thread.lastMessage.date` or something similar.

**Comment by saitodisse** [comment]
+1

**Comment by albandiguer** [comment]
related to this commit 
https://github.com/facebook/flux/commit/ca5d76d7511d87a48dd5802ff4663bba42747ae4

**Comment by piglovesyou** [comment]
This is already fixed in 86c4b7adac6b360370cbbe4413b9020b78625fd0

**Comment by kyldvs** [comment]
Cool, thanks for identifying that it's already fixed :)
