### ISSUE TITLE
wondering what this piece of code does

### ISSUE THREAD

**Issue by zzz6519003** [facebook/flux#228]
```
var invariant = function(condition, format, a, b, c, d, e, f) {
  if (false) {
    if (format === undefined) {
      throw new Error('invariant requires an error message argument');
    }
  }
```

  if (false) {

:beers:

**Comment by zpao** [comment]
[The original source](https://github.com/facebook/flux/blob/master/src/invariant.js#L26) has `if (__DEV__)` which we use to build development or prod builds (though in flux we're only building prod builds. Our build system here is very simple and just sticks `false` in there. React's is a bit fancier and sticks `process.env.NODE_ENV !== "production"` so it can be changed at runtime.
