### ISSUE TITLE
ALL Exception ignored during dispatching

### ISSUE THREAD

**Issue by speedfirst** [facebook/flux#231]
In https://github.com/facebook/flux/blob/master/src/Dispatcher.js line 194

The code here will "eat" all the exceptions. Is it as design or a bug?

```javascript
try {
      for (var id in this._callbacks) {
        if (this._isPending[id]) {
          continue;
        }
        this._invokeCallback(id);
      }
    } finally {
      this._stopDispatching();
    }
```

**Comment by kyldvs** [comment]
`finally` won't swallow the errors it will just make sure that we call `this._stopDispatcher()` before we throw any errors. I just tested throwing an exception from a function registered to a dispatcher and it threw and halted execution like normal.

Do you have example code where this is not the case?

**Comment by tomkis1** [comment]
@speedfirst I would guess you have your code wrapped in promise which swallows the exception. Try using Bluebird instead of Q or ES6 Promise.

**Comment by mikemorton** [comment]
The exceptions seem to be passed on to the application, it just seems like 'break on uncaught exception' doesn't work in chrome in this case.
