### ISSUE TITLE
ES6 + EventEmitter: adding and removing listeners

### ISSUE THREAD

**Issue by iNikNik** [facebook/flux#235]
Hello! I need help with removing event listener when my component "willUnmount":

```javascript
class SomeComponent extends Component {

    componentDidMount() {
      SomeStore.onStateChange(this.handleStateChangeEvent.bind(this));
    }

    componentWillUnmount() {
      // Error
      SomeStore.offStateChange(this.handleStateChangeEvent.bind(this));
    }

    render() {
      return <p>Hello!</p>;
    }

    handleStateChangeEvent() {
      this.forceUpdate();
    }
}
```

[React docs](https://facebook.github.io/react/docs/reusable-components.html#no-autobinding) says "No Autobinding" for ES6. 

As you can see - componentWillUnmount method does not remove the listener ...  what is the best way to resolve that?

**Comment by tleunen** [comment]
You have to keep a reference to your bound function.
```javascript
class SomeComponent extends Component
    constructor(props) {
        super(props);
        this._handleStateChangeEventBound = this.handleStateChangeEvent.bind(this);
    }
    componentDidMount() {
        SomeStore.onStateChange(this._handleStateChangeEventBound);
    }
    componentWillUnmount() {
        SomeStore.offStateChange(this._handleStateChangeEventBound);
    }
    // ...
}
```

**Comment by iNikNik** [comment]
Big thanks! I thought about it, but I could not find any information about storing custom data inside react components ... and I thought - it's antipattern)

**Comment by ginamdar** [comment]
I spent so much time to remove my function from Orientation.removeOrientationListener @tleunen thank you for your idea of keeping reference
