### ISSUE TITLE
action creator method must be called asynchronously

### ISSUE THREAD

**Issue by hon** [facebook/flux#248]
I've defined an action creator, and call some method direct in the view page (or in the constructor):
```javascript
    //action creator
    MaintenanceActions.initCarInfo({
      data: [{test:'test'}],
      source: settings.fluxSource.cache
    });
```
and listen to the event:
```javascript
    componentDidMount(){
      let initCallback = function(){
        console.log('init callback..');
      }
      //init
      MaintenanceStore.addInitListener(initCallback);
    }
```
the 'initCallback' function is not called. It seem that 
```javascript
  this.on('init_event', callback)
```
doesn't handle.

But, if I call 'MaintenanceActions.initCarInfo()' in an event handler, like click event, or a ajax callback, it works.

Must I call the action creator method asynchronously?

**Comment by changzhiwin** [comment]
I can't see any problem above your code. `initCallback ` will call when you create a action

**Comment by kyldvs** [comment]
You shouldn't need to call an action creator asynchronously. You will want to ensure that your store has registered itself with the dispatcher before calling your action creators synchronously though.

**Comment by hon** [comment]
Thanks, I should listen to the event, before the event is triggered:
```javascript
  componentDidMount(){
    let initCallBack = function(){
      console.log('init callback..');
    }
    // listen here, before event is triggered.
    MaintenanceStore.addInitListener(initCallBack);

    //触发action
    MaintenanceActions.initCarInfo({
      data: [{test:'test'}],
      source: settings.fluxSource.cache
    });
  }
```
It works as expected.

**Comment by kyldvs** [comment]
Awesome, glad you figured it out!
