### ISSUE TITLE
[CodeReview]Setting state from store vs setting state from component

### ISSUE THREAD

**Issue by MattMcFarland** [facebook/flux#261]
[In this highlighted code](https://github.com/facebook/flux/blob/master/examples/flux-chat/js/components/MessageComposer.react.js#L40-L42) I'm seeing that you are using setState to update the field value of the text input.  While I can understand that its a simple update, it kindof makes it difficult for me to see where you draw the line from setting state from store vs setting state from component itself.

I'm not sure how I feel about this approach.  If you set the state from the component in some places and then set the state *for the component* in a other places (like the store) - then it makes it a little blurry, I mean, how do you know where state is being set if it is coming from different places?  Isn't this an anti-pattern?  

If this is a "best practice" then why?  and when would you decide that something should be setting state from the store vs from the component?  IS there an established pattern or guideline here?

**Comment by kyldvs** [comment]
Check out the container concept in 2.1.1, http://facebook.github.io/flux/docs/flux-utils.html#containers

It should help you draw a clear line between state coming from stores and state coming from the component.

**Comment by MattMcFarland** [comment]
Thanks, but all I'm seeing is that container's do not rerender on state change and they are static, but the code I reviewed rerenders so I don't see the clear line... am I missing something?

**Comment by kyldvs** [comment]
Sorry, I'm confused about your question I guess. You mention setting state from a store but there is no store used in the file you reference. Perhaps if you could provide a counter-example to the above code with the change you would propose that would be helpful for me to understand your issues

**Comment by MattMcFarland** [comment]
Hey no worries!   I'm confused too :)

The problem I'm having is that other components in the same repo are using stores, and then this one isn't.  To me, it seems to break a convention, but I'm trying to understand if there is a best practice to where you should use a store or vice versa.

**Comment by kyldvs** [comment]
There isn't a strict convention. Generally you will have "smart" components that get information from stores and save it in their state. The smart components will then pass this information to "dumb" components via props. Dumb components may also maintain other state (such as user input) in addition to the information they receive via props as is seen here.

**Comment by MattMcFarland** [comment]
Thanks for the reply.  I guess these types of things trip me up some times :)  I'm trying to follow best practices.  I think there could be a convention per se, but not strict exactly.  I'm more or less thinking what the best practice would be with the goal being optimal scalability.

**Comment by kyldvs** [comment]
Yeah, we try to provide more guidance here: http://facebook.github.io/flux/docs/flux-utils.html#content

Note that the example you are looking at is older than this documentation so might not follow it completely. https://github.com/facebook/flux/tree/master/examples/flux-utils-todomvc is a newer example which should follow these best practices.

**Comment by MattMcFarland** [comment]
Thanks for the info.  I am really not sure how I feel about adding on those flux utilities, especially if I can acheive everything without them.  I'll process the information there though.
