### ISSUE TITLE
How dispatcher inheritance is supposed to work in 2.1.1?

### ISSUE THREAD

**Issue by hackhat** [facebook/flux#263]
After you added `function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }` how is supposed to inherit from the Dispatcher?

This code doesn't work anymore because the Constructor of the instance is now AppDispatcher instead of Dispatcher.

    var AppDispatcher = function () {
      Dispatcher.apply(this, arguments);
    };
  
    extend(AppDispatcher.prototype, Dispatcher.prototype, {
    });

**Comment by kyldvs** [comment]
Why not use classes and and extends?

```
class AppDispatcher extends Dispatcher {}
```

**Comment by hackhat** [comment]
I'm not using the new ES6 syntax. There is no old js way of doing that? I would not like to use all this huge thing: https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20AppDispatcher%20extends%20Dispatcher%20%7B%7D

**Comment by kyldvs** [comment]
Why do you need to extend AppDispatcher anyway?

For now I'd recommend just using 2.0.3 then, I'll look a bit into how we can support non ES6 environments.

**Comment by hackhat** [comment]
Yes, currently we are using the 2.0.3, but will not be able to upgrade very soon to the newest versions. I appreciate your help.

**Comment by kyldvs** [comment]
We will prefer ES6 classes for extending the Dispatcher going forward.

That said, in general you should not need to extend the Dispatcher. If you want additional functionality to happen on every action just register a callback with the dispatcher.
