### ISSUE TITLE
Changelog for 2.1?

### ISSUE THREAD

**Issue by tarjei** [facebook/flux#265]
Hi, what changed in flux 2.1? Have you guys considered keeping a simple changelog somewhere?

**Comment by kyldvs** [comment]
Sounds like a good idea. For now you can find documentation on what was added here: facebook.github.io/flux/docs/flux-utils.html#content

**Comment by kyldvs** [comment]
Here ya go: https://github.com/facebook/flux/blob/master/CHANGELOG.md

**Comment by tarjei** [comment]
Thanks a bundle!

2015-08-19 18:46 GMT+02:00 Kyle Davis <notifications@github.com>:

> Closed #265 <https://github.com/facebook/flux/issues/265>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/flux/issues/265#event-386739522>.
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413
