### ISSUE TITLE
FluxContainer.create() with default config {pure: true} does not work with react-router

### ISSUE THREAD

**Issue by davidye** [facebook/flux#266]
ReactRouter's <Link> and possibly other transition methods are broken when used in conjunction with FluxContainer

**Comment by kyldvs** [comment]
Looks like the same issue here: https://github.com/rackt/react-router/issues/470

If it doesn't get fixed in react-router or react itself we can try to address it. The workaround for now is to just not create containers as pure `Container.create(Foo, {pure: false})`

**Comment by gaearon** [comment]
### Updating the Views

That's pretty easy to fix: pass router state down to all route handlers.

[React Router 0.13 instructions](https://github.com/rackt/react-redux#my-views-arent-updating-on-route-change-with-react-router-013)
React Router 1.0 does this anyway, so no need to do anything special there

### Updating the `<Link>` state

That's the tricky one. I'd suggest keeping the router state in the Flux store and writing your own `<Link>` that reads from it to sidestep the issue completely.

**Comment by kyldvs** [comment]
Seems like there are a few workarounds, and this appears to be more appropriate as an issue with react-router than here.
