### ISSUE TITLE
Include src directory in npm package

### ISSUE THREAD

**Issue by Daniel15** [facebook/flux#272]
Currently the npm package only contains the `lib` directory, which is the compiled code after running Babel. This means it embeds the Babel helper functions like `_classCallCheck` and `_inherits` into the code. I'm using [external helpers](http://babeljs.io/docs/advanced/external-helpers/) to avoid repeating the Babel helpers throughout every file in my codebase, so it would be good to be able to do the same with Flux.  Including the `src` directory in the npm package would allow this - I could then just do `require('flux/src/FluxStore')` in my code and use my own version of Babel, while people that want to use the pre-compiled version (eg. if they're not using Babel) can do `require('flux/utils')` or `require('flux/lib/FluxStore')` :)

**Comment by zpao** [comment]
Going to close this out in favor of #304.

**Comment by Daniel15** [comment]
This is probably worth doing if/when we convert to ES6 modules, to take advantage of ES6 bundlers like [rollup](http://rollupjs.org/). Not sure if there's plans to convert to ES6 modules though.

**Comment by zpao** [comment]
Maybe. I think that's a FB-wide projects decision and we probably don't want to go making decisions just here.
