### ISSUE TITLE
Expose flux-utils through a bower package

### ISSUE THREAD

**Issue by adamsea** [facebook/flux#277]
Hello,

Is there any chance of getting flux-utils included into a tagged build?  Current dist/ includes dispatcher only (which is awesome) but it would be double -- heck even triple-awesome -- if some of the new store types were available to folks outside the Babel toolchain.

Thanks!
-Eric

**Comment by kyldvs** [comment]
It should still be usable after `npm install flux` by requiring `flux/utils`, or are you outside of a node environment completely?

**Comment by adamsea** [comment]
@kyldvs I'm running in a browser context, currently installing flux via bower.  It looks like immutable.js would need to be added as a dependency, and then if needed I could set up a bower post-install hook.

**Comment by zpao** [comment]
@kyldvs Took longer than I expected but I told you somebody would want it :wink:

**Comment by kyldvs** [comment]
Yeah looks like we need to add a second bower module that pulls in flux utils, you did call it @zpao  :P

**Comment by adamsea** [comment]
Ha well @zpao I posted something about this on Twitter about 2 weeks ago, just wasn't sure who to tag then! ;)  Glad to hear it'll make its way in.

**Comment by kuakman** [comment]
Yup, same thing. It would be nice to have flux/utils as part of the flux bower package.

@adamsea :thumbsup:

**Comment by kyldvs** [comment]
I have no idea how to have multiple bower packages in the same repo. I was just reading: https://bower.io/docs/creating-packages/

If someone wants to put up a PR/help with this I'm happy to accept them. The files are in /dist now.

**Comment by tiarebalbi** [comment]
I think this issue can be closed as bower has been deprecated right?
