### ISSUE TITLE
State modules or node as a requirement

### ISSUE THREAD

**Issue by gap** [facebook/flux#278]
With react I created a simple one page application with everything but libraries inlined to play with  concepts.  I am unable to do that with flux because it requires a module manager.

  I installed flux with bower 

    bower install flux

README.md has the statement "Flux is more of a pattern than a framework, and **does not have any hard dependencies**".  Yet, every example I have seen has the code

```javascript
var Dispatcher = require('flux').Dispatcher;
```
I have been unable to try with Flux because I have not gotten it's module manager working (browserify).  That sounds like a hard dependency.

I suggest either changing the requirements or provide a simple example how to use flux without any dependencies.

**Comment by kyldvs** [comment]
When you include the `dist/*` files via a script tag it will inject a global `Flux` variable that you can then use.

```
var Dispatcher = Flux.Dispatcher;
```
