### ISSUE TITLE
A separate repo for the Flux Chat example

### ISSUE THREAD

**Issue by d6u** [facebook/flux#280]
Hi, I just extracted the Flux Chat example into it's [own repo](https://github.com/d6u/flux-chat) and made numbers of changes to make it up to date. The reason I like to put it in its own repo is that I also working on Chat example for other Flux implementation, e.g. [Redux Chat](https://github.com/d6u/redux-chat). I don't know how you feel about this direction? Do you prefer a PR to update the example here or you are fine to add a link to (https://github.com/d6u/flux-chat)[https://github.com/d6u/flux-chat]?

Changes from original example:
- Update React.js to 0.14rc1
- Fixed some bugs, e.g. `latestMessage` on thread is not update when create new message
- Mock server latency when "fetching" messages (use setTimeout)
- Use ES6 syntax
- Consolidate actions into single file (`actions.js`)
- Webpack instead of Browserify
- Babel instead of Reactify

**Comment by kyldvs** [comment]
Any changes to the examples should be done through PR, hope that answers your question!
