### ISSUE TITLE
Optionally pass props to (a non-static) getStores()

### ISSUE THREAD

**Issue by jamiehodge** [facebook/flux#281]
Would there be any objections to a pattern similar to calculateState's withProps option, where getStores would a) no longer be static and b) be passed the current props? This would allow non-singleton/passed stores.

**Comment by kyldvs** [comment]
I'm not opposed to the idea, but what is the purpose of (a). What does it being static have to do with passing in props or not?

**Comment by kyldvs** [comment]
Although I'm also looking at ways to remove `getStores()` all together so that containers will just automatically subscribe to stores used within `calculateState()`. So this might not be necessary in the future.

**Comment by kyldvs** [comment]
Resolved in latest updates to container: https://github.com/facebook/flux/blob/master/src/container/FluxContainer.js#L83-L86
