### ISSUE TITLE
flow finds errors in example flux-utils-todomvc

### ISSUE THREAD

**Issue by destan** [facebook/flux#285]
flow version `0.16.0`
node version `v0.12.7`

steps to reproduce:

* checkout https://github.com/facebook/flux/tree/master/examples/flux-utils-todomvc
* run `npm install`
* download flow (https://facebook.github.io/flow/downloads/flow-linux64-latest.zip)
* run `~/Downloads/flow/flow check`

```
/home/user/projects/flux/examples/flux-utils-todomvc/js/components/Footer.react.js:26:12,16: todos
const cannot be reassigned
/home/user/projects/flux/examples/flux-utils-todomvc/js/components/Footer.react.js:26:11,30: const todos

/home/user/projects/flux/examples/flux-utils-todomvc/js/components/Footer.react.js:28:5,30:5: todos
const referenced before declaration
/home/user/projects/flux/examples/flux-utils-todomvc/js/components/Footer.react.js:26:11,30: const todos

/home/user/projects/flux/examples/flux-utils-todomvc/js/components/Footer.react.js:28:9,13: todos
const referenced before declaration
/home/user/projects/flux/examples/flux-utils-todomvc/js/components/Footer.react.js:26:11,30: const todos

/home/user/projects/flux/examples/flux-utils-todomvc/js/components/Header.react.js:16:27,49: TodoTextInput.react.js
Required module not found

/home/user/projects/flux/examples/flux-utils-todomvc/js/components/MainSection.react.js:35:14,23: Destructuring assignment must be initialized

/home/user/projects/flux/examples/flux-utils-todomvc/js/components/TodoApp.react.js:26:25,45: MainSection.react.js
Required module not found

/home/user/projects/flux/examples/flux-utils-todomvc/js/components/TodoItem.react.js:35:3,8: Unexpected identifier

/home/user/projects/flux/examples/flux-utils-todomvc/js/components/TodoTextInput.react.js:36:3,8: Unexpected identifier

/home/user/projects/flux/examples/flux-utils-todomvc/node_modules/flux/flow/include/FluxStoreGroup.js:55:7,13: identifier __DEV__
Could not resolve name

Found 9 errors

```

Why is that and how can we fix it?

**Comment by kyldvs** [comment]
Yup when I wrote it let/const was not supported in flow so it was not possible to commit it with flow being clean. Now that flow has support for let/const it should be possible to get it clean.

**Comment by destan** [comment]
@kyldvs flow documentation says it supports [es6 features](https://github.com/facebook/flow/issues/560) already. What should I do to clean those?  would you point me to the right direction please?

PS: the error doesn't seem to be of let/cons though...

**Comment by mhagmajer** [comment]
@kyldvs, I'm getting this errors with the latest Flow 0.18.1 for that example project.

```
js/components/Header.react.js:16
 16: import TodoTextInput from './TodoTextInput.react';
                               ^^^^^^^^^^^^^^^^^^^^^^^ TodoTextInput.react.js. Required module not found

js/components/MainSection.react.js:19
 19: import TodoItem from './TodoItem.react';
                          ^^^^^^^^^^^^^^^^^^ TodoItem.react.js. Required module not found

js/components/TodoItem.react.js:35
 35:   render(): ?ReactElement {
       ^^^^^^ Unexpected identifier

js/components/TodoTextInput.react.js:36
 36:   render(): ?ReactElement {
       ^^^^^^ Unexpected identifier

node_modules/flux/flow/include/FluxStoreGroup.js:55
 55:   if (__DEV__) {
           ^^^^^^^ identifier `__DEV__`. Could not resolve name
```

Some errors seem to be related to the fact that you're using babel stage 0 that includes [Proposal: ES Class Fields & Static Properties](https://github.com/jeffmo/es-class-static-properties-and-fields) which Flow doesn't support.

**Comment by lukescott** [comment]
I'm having these errors as well. Also, isn't this supposed to be an error?
```javascript
const instance: Dispatcher<Action> = new Dispatcher();
export default instance;

instance.dispatch(5); // <--- not showing as error
```

I've been trying nuclide-flow and it seems like nothing on the Dispatcher instance is showing up for the auto-complete either.

**Comment by camspiers** [comment]
@lukescott if you have a look at the contents of the Dispatcher file that is installed via npm, I think you'll find that it doesn't have the flow types in it. I think that is what explains the missing error in your case.

**Comment by lukescott** [comment]
@camspiers There is some sort of field def here:
https://github.com/facebook/flux/blob/master/examples/flux-utils-todomvc/.flowconfig#L10

That directory does contain a Dispatcher file, although I'm not sure how that works exactly. There is no index.js file in the flux/flow/include directory. There is also a definition for __DEV__ in flux/flow/lib, but flux isn't able to resolve it.

**Comment by camspiers** [comment]
Unsure how the include is meant to work. @kyldvs any ideas?

**Comment by kyldvs** [comment]
I opened #297 to track that issue since it is separate from what this was originally opened for. It looks to me like that is how the flowconfig should be set up so i'll have to dig into it a bit more.

**Comment by eikeon** [comment]
With flow 0.22.1 I'm getting 25 errors mostly along the lines of:

```
citta:flux-utils-todomvc eikeon$ flow
Launching Flow server for /private/tmp/flux/examples/flux-utils-todomvc
Spawned flow server (child pid=78961)
Logs will go to /private/tmp/flow/zSprivatezStmpzSfluxzSexampleszSflux-utils-todomvc.log
js/components/Footer.react.js:24
 24: export default class Footer extends Component<{}, Props, {}> {
                                                   ^^ object type. This type is incompatible with
 24: export default class Footer extends Component<{}, Props, {}> {
                                                   ^^ undefined. Did you forget to declare object type?
```

Has anyone been able to get this example to work? Or have any idea for pointing me in the right direction.

**Comment by kyldvs** [comment]
The example should run fine, the flow types are not correct. If the example does not work let's open another issue to track it, if the example does work and just reports some flow errors that's what this issue is meant to be tracking.

**Comment by eikeon** [comment]
The example is running fine for me. I'll fix my wording at the end. It's the flow errors that I'm trying to get working. Think I may have just figured out what is causing most of them. Looking at the HOC class at the end of http://flowtype.org/docs/react.html#_ I noticed it has a state property. Adding these to Footer etc is at least part of the fixes needed. I'll see if I can put together a pull request.

**Comment by kyldvs** [comment]
Awesome! Thanks for looking into it. A pull request would be great.

**Comment by kyldvs** [comment]
#336 should have fixed this!
