### ISSUE TITLE
The code in here does not seem in sync with what's described on the web page

### ISSUE THREAD

**Issue by aravantv** [facebook/flux#286]
The code in here does not seem in sync with what's described on the web page:
https://facebook.github.io/flux/docs/todo-list.html
For instance the dispatcher does not have the same content, and using react-boilerplate seems to bring an "src" directory rather than a "js" directory.

**Comment by aravantv** [comment]
To clarify, this issue is specific to the tutorial "TODO MVC".

**Comment by vmaudgalya** [comment]
+1

**Comment by theodorecackowski** [comment]
+1

**Comment by irudoy** [comment]
+1 This tutorial is outdated :(

**Comment by sylvainlap** [comment]
+1

**Comment by kyldvs** [comment]
Removed this tutorial in favor of: https://github.com/facebook/flux/tree/master/examples
