### ISSUE TITLE
Mistake in the flux-chat example?

### ISSUE THREAD

**Issue by tomnewton** [facebook/flux#300]
Took a look at the chat example that is included in this project to help get familiar with Flux. 

Correct me if I'm wrong... but I don't think the ActionType.RECEIVE_RAW_CREATED_MESSAGE which is dispatched from ChatServerActionCreator is observed by anyone?

**Comment by zpao** [comment]
See #32. It looks like that's left in there as an exercise (though it could probably use some inline comments to that effect). cc @kyldvs
