### ISSUE TITLE
Should I put all states and props inside Store?

### ISSUE THREAD

**Issue by littlee** [facebook/flux#301]
I trying to use flux in my current project, and I get a little confused,

When implementing Flux, should I put all state and props inside a `store`, and the components just get state and props from store every single time?

Or I could put some of the states and props inside components' code, and merge it with the states and props from store, and then provide to components?

**Comment by kyldvs** [comment]
You should generally choose one or the other for any single component. Either get the component's state purely from stores, or have a component maintain it's own state. Merging of state will likely lead to a mess.

**Comment by littlee** [comment]
:+1:
