### ISSUE TITLE
What's the best location to call data fetching functions?

### ISSUE THREAD

**Issue by littlee** [facebook/flux#302]
I trying to imitate the examples provided in flux repo to do data fetching in my project,
so I create some XXXUtil.js to do data fetching.
and I call the initial data fetching in the bootstrap file (app.js in my case).

but I am doing a large SPA, so I use react router to do components lazy load,
I don't want to load all the data for all components at the bootstrap file in the first time,
so where can I call some other util methods to fetch data for other components which will render later?

**Comment by kyldvs** [comment]
This is a good example that uses async data fetching with the flux infrastructure here: https://github.com/staltz/flux-challenge/tree/master/submissions/kyldvs
