### ISSUE TITLE
Add Flow declaration files

### ISSUE THREAD

**Issue by Daniel15** [facebook/flux#304]
So that people using Flux via the compiled files in the npm package can get Flow typing.

http://flowtype.org/blog/2015/12/01/Version-0.19.0.html#declaration-files

**Comment by zpao** [comment]
I just did this for fbjs (https://github.com/facebook/fbjs/pull/83). Feel free to do the exact same thing.

**Comment by kyldvs** [comment]
Should be resolved by #319
