### ISSUE TITLE
Loading data on app load

### ISSUE THREAD

**Issue by goofiw** [facebook/flux#306]
There doesn't seem to be a way to make one ajax call once on app load, sort of like a appDidMount function.  

I know I should be doing this in a top level component, unfortunately I'm using a bootstrap wrapper that does not have a top level component (which is rather frustrating, but I'm stuck with it).

Any hacky solutions?

**Comment by sterpe** [comment]
@goofiw:  Use a mutationObserver?

**Comment by vanhtuan0409** [comment]
How about making another Wrapper for your bootstrap wrapper and fire Actioni to fetch data from that Wrapper.
Dont know if I misunderstanding your question

**Comment by koolaidfinesse** [comment]
@goofiw `componentDidMount` or `componentWillMount` but then if you're planning on building a universal app you'll have to pass the initial state to the client when you render the template.

**Comment by kyldvs** [comment]
Yeah componentWillMount/componentDidMount should handle this case fine. Example: https://github.com/staltz/flux-challenge/blob/master/submissions/kyldvs/src/AppContainer.js#L31

If you run into issues with using these functions it may be related to #316 which I hope to get to in the next release.
