### ISSUE TITLE
How does ActionTypes.RECEIVE_RAW_MESSAGES suddenly appears in FluxChat app?

### ISSUE THREAD

**Issue by wzup** [facebook/flux#312]
I cannot understand where is the point at which server side data (messages, threads) appear in the app. Where is that line of code that fetches data from the server (or in this case from localStore)?

Here is how initial state of MessageSection is created. And how `MessageStore.getAllForCurrentThread(),` looks like:

```
// MessageSection.js
function getStateFromStores() {
    return {
        messages: MessageStore.getAllForCurrentThread(), // this should return the data
        thread: ThreadStore.getCurrent()
    };
}
```

Here is `MessageStore.getAllForCurrentThread()`. There is no data in `_messages`, this `for/in` just do nothing. How does the data appears in the system, in `_messages`?

```
  /**
   * @param {string} threadID
   */
  getAllForThread: function(threadID) {
    var threadMessages = [];
    for (var id in _messages) {
      if (_messages[id].threadID === threadID) {
        threadMessages.push(_messages[id]);
      }
    }
    threadMessages.sort(function(a, b) {
      if (a.date < b.date) {
        return -1;
      } else if (a.date > b.date) {
        return 1;
      }
      return 0;
    });
    return threadMessages;
  },
```

**Comment by shaoner** [comment]
@wzup, there is an action for this, called `CREATE_MESSAGE`, which is then passed to the MessageStore callback (using the dispatcher).
Then, the MessageStore internally adds the new message:
```javascript
_messages[message.id] = message;
```
If there is no messages, an empty array is returned.

**Comment by kyldvs** [comment]
This is no longer relevant, chat example is gone and replace with new async tutorial here: https://github.com/facebook/flux/tree/master/examples
