### ISSUE TITLE
Npm package fails on install

### ISSUE THREAD

**Issue by mylonasg88** [facebook/flux#315]
Running ```npm install``` it fails on some of dependencies.
[npm-debug.txt](https://github.com/facebook/flux/files/97974/npm-debug.txt)

OS X `El Capitan Version 10.11.2 `
npm -v `2.14.4`
node -v `v4.1.2`

**Comment by zpao** [comment]
Please describe your OS, node version, npm version, and directory you ran `npm install` from so that somebody can try to reproduce the issue.

**Comment by mylonasg88** [comment]
OS X `El Capitan Version 10.11.2 `
npm -v `2.14.4`
node -v `v4.1.2`

**Comment by kyldvs** [comment]
I recently did a fresh pull and `npm install` and everything works fine. Please reopen if you are still experiencing issues with latest version of npm and node.

```
npm: 3.7.3
node: v5.9.1
```
