### ISSUE TITLE
Creating a dispatcher example - problematic use of promise

### ISSUE THREAD

**Issue by benjamingr** [facebook/flux#318]
Hi, in the example here: https://facebook.github.io/flux/docs/todo-list.html#creating-a-dispatcher 

The dispatcher you create completely ignores promises failing. The error thrown is just swallowed by the promise chain and is suppressed so you don't get _any_ useful info if there is an error. This can be very frustrating for newcomers.

You're also performing [explicit construction](http://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it) there that could be easily by turning this:

```js
dispatch: function(payload) {
    var resolves = [];
    var rejects = [];
    _promises = _callbacks.map(function(_, i) {
      return new Promise(function(resolve, reject) {
        resolves[i] = resolve;
        rejects[i] = reject;
      });
    });
    _callbacks.forEach(function(callback, i) {
      Promise.resolve(callback(payload)).then(function() {
        resolves[i](payload);
      }, function() {
        rejects[i](new Error('Dispatcher callback unsuccessful'));
      });
    });
    _promises = [];
  }
```

Into:
```js
dispatch: function(payload) {
    _promises = Promise.all(_callbacks.map(callback =>callback(payload)).map(Promise.resolve));
}
```

Or if you insist on suppressing errors:

```js
dispatch: function(payload) {
    _promises = Promise.all(_callbacks.map(callback => callback(payload)).map(Promise.resolve)
                                                                            .catch(x => { throw new Error(...)})));
}
```

I'd write a PR (keeping the docs and having less terse syntax) gladly - I just don't know where the example is and was unable to locate it on the repo.

**Comment by benjamingr** [comment]
Actually that `.all` doesn't keep the original semantics - so should probably remove that.

**Comment by kyldvs** [comment]
This seems to be the same issue as #286.

**Comment by benjamingr** [comment]
@kyldvs no, this issue is about what being there being _wrong_, not about it being missing. Being missing is a side effect of me trying to _fix it_.

**Comment by kyldvs** [comment]
That issue explicitly calls out the section on dispatchers as needing improvement because it is nothing like how we create dispatchers now. General cleanup of that section will resolve your more specific issue with it.
