### ISSUE TITLE
Outdated fbjs dependency in flux npm module

### ISSUE THREAD

**Issue by wialy** [facebook/flux#329]
When installing flux via `npm`, there is a `"fbjs": "0.1.0-alpha.7"` in flux's package json. 

This issue causes an `Error building DependencyGraph` error while using react-native packager.

node version: v5.5.0
npm version: 3.7.1

**Comment by kyldvs** [comment]
Chasing dependencies kind of sucks, @ide how can we make this work for react native so that we don't have to arbitrarily update dependencies when we don't need to?

**Comment by ide** [comment]
Yes, React Native will be updated in the coming weeks (ETA 2-4 wks till release). The PR is ready but FB is having issues merging it so thanks for your patience.

**Comment by kyldvs** [comment]
Awesome! So in ~1 month this will be fixed from react natives side?

**Comment by ide** [comment]
Yes -- the plan is to fix a bug and allow different copies of fbjs to co-exist under node_modules.

**Comment by tristangodfrey** [comment]
Is there a workaround for this?

**Comment by ide** [comment]
Fork this repo, update the deep, use your fork.

**Comment by kyldvs** [comment]
Is there a particular version we can update to for now just to unblock this? Is it still `^0.6.0` like you did here: https://github.com/facebook/emitter/pull/16 ?

**Comment by vladp** [comment]
+1 on the issue
Prevents alt  from being used in react-native (and a number of react-native demo apps that use alt)

`-- alt@0.18.2
  +-- flux@2.1.1
  | +-- fbemitter@2.0.2
**  | `-- fbjs@0.1.0-alpha.7
**  +-- is-promise@2.1.0
  `-- transmitter@1.1.0

**Comment by tristangodfrey** [comment]
Is this fixed in react native `0.21`?

**Comment by ljhender** [comment]
@tristangodfrey - Not fixed as of RN 0.21, I'm trying to upgrade my project now and still getting this conflict.

**Comment by sethx** [comment]
Can we PLEASE fix this? @kyldvs i get that chasing dependencies is a chore, but breaking tons of builds for users is just evil.

**Comment by ide** [comment]
Submit a PR + test plan if this is important to you. On the fbemitter repo @kyldvs was receptive to merging dep upgrades w/ a responsible test plan.

**Comment by sethx** [comment]
Please suggest an actionable test plan. I'll gladly submit a PR for the
package.json .

**Comment by ide** [comment]
`npm test` is a good start. Also verifying that it works in a complex app is another good test.

**Comment by wialy** [comment]
For now, this is what helps: 
```
rm -rf ./node_modules/fbemitter/node_modules/fbjs
rm -rf ./node_modules/flux/node_modules/fbjs
rm -rf ./node_modules/react/node_modules/fbjs
rm -rf ./node_modules/react-native/node_modules/fbjs
watchman watch-del-all
rm -rf $TMPDIR/react-packager-*
```
I have added this code to package.json as a npm task `clean`, because every time I install a package via npm, it also installs missing fbjs, so this fix is pretty often used.

**Comment by kyldvs** [comment]
Yes, feel free to submit a PR. I don't use react-native so I simply don't know how to update this in such a way to unblock everyone.

**Comment by kyldvs** [comment]
If https://github.com/facebook/flux/pull/326 fixes react native we can just go with that.

**Comment by sethx** [comment]
That really would!

**Comment by sethx** [comment]
It's just the alpha dependency that triggers a conflict, because NPM thinks it has to install two versions of it, and spits out a warning about it.

**Comment by zpao** [comment]
I doubt it's just the alpha dep, it's likely any dep that doesn't match exactly what react-native uses. It's a stupid thing the chase but might be necessary short-term.

**Comment by kyldvs** [comment]
Updated to 0.8.0 here: https://github.com/facebook/flux/commit/ba9d6b7296d572ed7d1af5a54b8d0637f3986b84
