### ISSUE TITLE
Syntax error when running through browserify

### ISSUE THREAD

**Issue by landed1** [facebook/flux#330]
src/libs/dispatcher.js: Missing class properties transform. while parsing file: src/libs/dispatcher.js

I am sorry that I am a little unsure why this is happening I am trying to include using browserify like this 

`var bundler = browserify([config.js.src+"/app.jsx",
                            "src/libs/dispatcher.js",
                            "src/libs/microevent.js"],
                            args) // Browserify
    .plugin(watchify, {ignoreWatch: ['**/node_modules/**', '**/bower_components/**']}) // Watchify to watch source file changes
    .transform(babelify, {presets: ['es2015', 'react']}); // Babel tranforms`

Thank you

**Comment by kyldvs** [comment]
Sounds like you are not transforming classes?

This is exactly how we transform each file: https://github.com/facebook/flux/blob/master/Gulpfile.js#L24-L64

Or you can just use the pre-transformed dist file: https://github.com/facebook/flux/blob/master/dist/Flux.js

**Comment by kyldvs** [comment]
Since we've also used browserify on the Dispatcher in the past this doesn't seem like a Flux issue, but rather a setup issue. Going to close this.
