### ISSUE TITLE
_isPending silent ignore

### ISSUE THREAD

**Issue by halt-hammerzeit** [facebook/flux#335]
WTF's this
https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L188-L190

```
        if (this._isPending[id]) {
          continue;
        }
```

Why no warning?

**Comment by halt-hammerzeit** [comment]
To further express my dissatisfaction I'd note that in a properly designed dispatcher `this.emitChange()` should be implemented inside the base implementation of a store and `this.emitChange()` call should be made after `_isPending[id]` is cleared.

**Comment by kyldvs** [comment]
This enables waitFor.
