### ISSUE TITLE
Initial state defined in component constructor is ignored when using FluxContainer

### ISSUE THREAD

**Issue by PabloDiablo** [facebook/flux#338]
When a component is wrapped in a FluxContainer class, its initial state defined in its constructor is ignored.

This doesn't seem like it should be expected behaviour as it makes it difficult for a component to have state properties that don't come from a store.

Consider this component:
```javascript
import React, {Component} from 'react';
import {Container} from 'flux/utils';

import DataStore from '../stores/DataStore';
import {getData} from '../actions/DataActions';

class App extends Component {

    constructor(props) {
        super(props);

        this.state = {
            modeIsOn: true
        };

        this.changeMode = this.changeMode.bind(this);
    }

    static getStores() {
        return [DataStore];
    }

    static calculateState(prevState) {
        return {
            isLoading: DataStore.get('isLoading'),
            itemCount: DataStore.get('items').length
        };
    }

    changeMode() {
        this.setState({
           modeIsOn: !this.state.modeIsOn
        });
    }

    render() {
        return (
            <div>
                <h1>Hello</h1>
                <p>Mode is { this.state.modeIsOn ? 'ON' : 'OFF' }</p>
                <p>Items: { this.state.isLoading ? 'LOADING...' : this.state.itemCount }</p>
                <button onClick={getData}>Get Data</button>
                <button onClick={this.changeMode}>Change Mode</button>
            </div>
        );
    }

}

export default Container.create(App);
```

In this instance `this.state.modeIsOn` will be `undefined` rather than the expected `true` until the `this.changeMode` function is called.

From looking at the code for FluxContainer, it would be easy to change this behaviour to take the initial state defined in the component constructor and merge the return value of `calculateState` into it.

FluxContainer.js
```javascript
constructor(props: any) {
      super(props);
      this.state = realOptions.withProps
        ? Base.calculateState(null, props)
        : Base.calculateState(null, undefined);
    }
```

Suggested change
```javascript
constructor(props: any) {
    super(props);
    var calculatedState = realOptions.withProps
        ? Base.calculateState(null, props)
        : Base.calculateState(null, undefined);

    this.state = {
        ...this.state,
        ...calculatedState
    };
}
```

I'm happy to submit a PR for this (I've already forked it and made the change) but I wanted to check this wasn't actually expected behaviour.

**Comment by kyldvs** [comment]
Thanks for the detailed explanation. I'm not entirely convinced this change is necessary, or a good thing for a few reasons. Mainly because I do not think that containers should have any state that is not described by `calculateState()`. Their sole purpose should be connecting data from stores to a view.

Would one of these solutions work for you?

```js
static calculateState(prevState) {   
    return {
        modeIsOn: prevState.modeIsOn == null ? true : prevState.modeIsOn,
        isLoading: DataStore.get('isLoading'),
        itemCount: DataStore.get('items').length
    };
}
```

```js
static calculateState(prevState) {   
    const init = prevState ? {} : {
        modeIsOn: true,
    };
    return {
        ...init,
        isLoading: DataStore.get('isLoading'),
        itemCount: DataStore.get('items').length
    };
}
```

**Comment by PabloDiablo** [comment]
Your suggested solution is essentially how I've gotten around this issue. I would have thought though that the fact this solution is possible shows that my change isn't adding any real functionality that isn't already possible - it's merely cleaning up the API and making it consistent with all other React components.

To be honest, I'd say the main problem with this is that it breaks functionality described in React documentation without explanation. The documentation for FluxUtils doesn't mention that this won't work. I've actually been using FluxContainers in production on two huge applications for months and I only noticed this issue today!

**Comment by kyldvs** [comment]
Fair enough :) Happy to accept a PR making the change you described then.

**Comment by PabloDiablo** [comment]
Thanks Kyle. I'll submit it now :)

**Comment by PabloDiablo** [comment]
Thanks for this Kyle. When do you think this will make it into a release and uploaded to NPM?

**Comment by kyldvs** [comment]
No promises, but I'll try to work on getting this and some other changes ready for a publish later today. I also have added a test for this case along with some updates to FluxContainer here: https://github.com/facebook/flux/blob/master/src/container/__tests__/FluxContainer-test.js#L166-L201
