### ISSUE TITLE
Flux Utils TodoMVC does not work 

### ISSUE THREAD

**Issue by singhshashi** [facebook/flux#341]
The current code for the flux-utils-todomvc does not work. Nothing happens on typing. On trying to debug this, I see that the render function for TodoTextInput component does not get called after calling setState, which is very odd. I do not know why this is happening, however if you revert the changes from https://github.com/facebook/flux/commit/8834112e49b8839f6e5c6e6fc8371ccadc7a5f00 it works fine.

**Comment by kyldvs** [comment]
Very strange, thanks for the report. I'll look into it.

**Comment by singhshashi** [comment]
I checked the commit from @piglovesyou and it resolves this issue. This made me dig deeper as to why the commit https://github.com/facebook/flux/commit/8834112e49b8839f6e5c6e6fc8371ccadc7a5f00 broke the app, which was working before. And I noticed that earlier, @kyldvs was autobinding the functions as described at http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding, which was changed in the commit  https://github.com/facebook/flux/commit/8834112e49b8839f6e5c6e6fc8371ccadc7a5f00 which broke the app,as now there was no autobinding.

**Comment by kyldvs** [comment]
Makes perfect sense. Thanks for the explanation.
