### ISSUE TITLE
multiple components in same page are influenced with each other, bugs

### ISSUE THREAD

**Issue by xhe** [facebook/flux#350]
I am using same component multiple times in the same page, and I just realized that any event dispatched are intercepted by all the same companents and all the components are updated together.
This is not acceptable, as even if it is same component, if it is used to display different data, they should have totally independent behavior. Action performed in one component should never be listened by another component.
How can I fix this error?

**Comment by kyldvs** [comment]
Your question is not clear at all. Try providing more clear details with a **minimal** code example to demonstrate the problem you are having.

Flux is the global state of your application. Each store receives every action, and every container is talking to the same set of stores.
