### ISSUE TITLE
Pass initial state to store constructor

### ISSUE THREAD

**Issue by edorivai** [facebook/flux#355]
When instantiating a store which is extending `ReduceStore`, I would like to be able to pass the initial state as a constructor variable.

My use case involves injecting some part of the initial state at the server side through window variables, like so:

``` JS
var initialState = {{ server injects state object here }};
```

I could access the window var in `getInitialState`, but I'd rather have my store be unaware of the window, and this method of injecting initial state.

Am I missing something? Is there any way of injecting state from outside of the store, apart from firing some `INITIALIZE` action?

**Comment by alexeyraspopov** [comment]
@edorivai, where do you instantiate stores?

**Comment by edorivai** [comment]
@alexeyraspopov Well I have this entrypoint file where I render all of my top level components. This is where I'd wish to instantiate my stores as well.

**Comment by piglovesyou** [comment]
I'm also curious how server-side rendering injects data into ReduceStore.

**Comment by piglovesyou** [comment]
Here is [how I do](https://github.com/piglovesyou/react-server-side-rendering-with-css-modules/blob/55ba3be3e61b5490411265850ef95b81fb3c3093/src/express.js#L49) (still wip).  Because it's usual to deal with ReduceStore as singleton, I let it be in server-side and just inject data before a use and clean it right afterward, even though I didn't like it.

I guess that Flux Container has to have a data injection point for server-side rendering, with using [context](https://facebook.github.io/react/docs/context.html) or something. If it does we don't have to care stores instantiation.

**Comment by kyldvs** [comment]
I don't think we are likely to change this. InitialState is really meant to be an empty state, not where you initialized the data for the store. It's expected that you return something like an empty map, then initialize you data through an action. The initial state should be constant all the time.

This helps to ensure the state of your flux application is a pure function of actions, so you could theoretically record and replay them to get in the same state. If you move the initialization out of the chain of actions that is no longer possible.

In any case there is a workaround if you need to have it behave in that manner, I believe this will work:

```
class FluxReduceStore2 extends FluxReduceStore {
  constructor(dispatcher, initialState) {
    super(dispatcher);
    this._state = initialState;
  }
  getInitialState() {
    return undefined;
  }
}
```

**Comment by cristinallamas** [comment]
Hi, if getInitialState is supposed to be an empty state, where would you initialise the store data? I'm a bit lost


```
class MusicStore extends ReduceStore{

  constructor() {
  super(Dispatcher);

   this.state = {
    list:[],
    favorites:[]
  };
 }

 getInitialState() {
   return [];
  }
...

}
```

where would I pass initial data to my this.data object?

**Comment by kyldvs** [comment]
If your "empty" state has a list and favorites you would write:

```
getInitialState() {
  return {
    list: [],
    favorites: [],
  };
}
```

To do the initial data fetching you would fetch data in the componentWillMount of the relevant component and then dispatch an action that the store responds to.
