### ISSUE TITLE
why use ChatWebAPIUtils  on app.js ?? [flux-chat]

### ISSUE THREAD

**Issue by victor-web** [facebook/flux#356]
why call getAllMessages on view ??

https://github.com/facebook/flux/blob/master/examples/flux-chat/js/app.js#L23

isn't better to have an action to do this??

**Comment by kyldvs** [comment]
From #187 

> The server interaction is getting faked with local storage in the chat app. I wouldn't take it too seriously.

Firing an action instead sounds reasonable too.

**Comment by victor-web** [comment]
sounds  not real world.
