### ISSUE TITLE
Why not update the example 'flux-todomvc'?

### ISSUE THREAD

**Issue by zhouzhongyuan** [facebook/flux#361]
## react 12.2

When I clone the repo, run the example, everything is ok, except:
In the Chrome console, it warning:

``` error
backend.js:8266 You are using a version of React with limited support in this version of the devtools.
Please upgrade to use at least 0.13, or you can downgrade to use the old version of the devtools:
instructions here https://github.com/facebook/react-devtools/tree/devtools-next#how-do-i-use-this-for-react--013
```

The url [https://github.com/facebook/react-devtools/tree/devtools-next#how-do-i-use-this-for-react--013](https://github.com/facebook/react-devtools/tree/devtools-next#how-do-i-use-this-for-react--013) can not be open.

I know it is because this todomvc use the react 12.2 (in the package.json).If I update react to 13.0 or above, the error will gone off.
## react15.0

_But_ when I update react to 15.0, another error appears in the Chrome. The error is:

``` error
warning.js:46Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.
```

I think this todomvc example is for beginners. 
So why not update the code ?

**Comment by esafwan** [comment]
This was huge issue for me when I started off. I spend a lot of time debugging this when all I wanted was to understand React.

**Comment by kyldvs** [comment]
I'm working on updating the examples, should be coming soon. Just need to polish up the documentation on it

**Comment by conmute** [comment]
Test for todomvc are also failing.

```
$ npm run test

> todomvc-flux@0.0.3 test /home/roman/Documents/projects/playground/flux-react/flux/examples/flux-todomvc
> jest

Using Jest CLI v0.4.19
 FAIL  dispatcher/__tests__/AppDispatcher-test.js
TypeError: Cannot read property 'length' of undefined
  at maybeReadMore_ (_stream_readable.js:451:18)
  at /home/roman/Documents/projects/playground/flux-react/flux/examples/flux-todomvc/node_modules/jest-cli/src
/lib/FakeTimers.js:342:7
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

/home/roman/Documents/projects/playground/flux-react/flux/examples/flux-todomvc/node_modules/node-worker-pool/
Worker.js:106
    throw new Error('Received unexpected data from child process: ' + data);

...

```

**Comment by kyldvs** [comment]
Everything should be updated here: https://github.com/facebook/flux/tree/master/examples

Let me know if you still have issues.
