### ISSUE TITLE
can  store have  multiple instances ?

### ISSUE THREAD

**Issue by victor-web** [facebook/flux#362]
With singleton stores, how do you prevent all components listening to a certain store from re-rendering when only one of them has updated?

example:
app like instagram that have a list of  photos and  each item  have actions that change only one of them  like  'favorite"
**ps**: all items in **same view**
**ps**: without **shouldComponentUpdate** 

@kyldvs  how solve this?   multiple instances ?

**Comment by kyldvs** [comment]
We use FluxContainer, you can see how we build our applications by following the examples here: https://github.com/facebook/flux/tree/master/examples
