### ISSUE TITLE
Using Flowtype with Flux

### ISSUE THREAD

**Issue by alexeyraspopov** [facebook/flux#365]
How to use Flowtype with Flux? What should `node_modules/flux/flow` folder do?

It's unclear and seems to be not documented anywhere? Correct me if I wrong.

**Comment by kyldvs** [comment]
Yeah, I'm not sure how yet either :)

I'm planning to set up a specific example on how to set up a repository using flux+flow though: Progress is over here at the moment: https://github.com/kyldvs/flux/tree/docs/examples/flux-flow

**Comment by kyldvs** [comment]
I use it like this: https://github.com/facebook/flux/tree/master/examples/flux-flow seems okay
