### ISSUE TITLE
react Dispatcher.dispatch in action, not dispatching payload to store

### ISSUE THREAD

**Issue by rosnk** [facebook/flux#368]
I have setup payload in "action", with the intention to dispatch api data to the store. But switch case is not triggered inside Dispatcher.register.

Flux version: "flux": "^2.1.1",

1) action file: (note: have confirmed that receivedAllServices is triggered by using debugger )

```
"use strict"

var Dispatcher = require('../dispatcher/appDispatcher');
// var requestActions = require('./requestActions');
var ActionTypes = require('../constants/actionTypes');

var ResponseActions = {

    receivedAllServices: function(all_services){

        console.log('response received');
        debugger;

        Dispatcher.dispatch({
            actionType: ActionTypes.RECEIVED_ALL_SERVICES,
            services: all_servicess
        });
    }



};

module.exports = ResponseActions;
```

2) Store: (note: debugger inside store action is not triggered )

```
Dispatcher.register(function(action){
    switch(action.actionType){
        case ActionTypes.RECEIVED_ALL_SERVICES:

            debugger;

            // AuthorStore.emitChange();
            break;
    }
});
```

3) Dispatcher file:

```
var Dispatcher = require('flux').Dispatcher;

module.exports = new Dispatcher();
```

4) actionTypes.js file

```
"use strict"

var keyMirror = require('fbjs/lib/keyMirror');

module.exports = keyMirror({
    RECEIVED_ALL_SERVICES: null, 
});
```

**Comment by alexeyraspopov** [comment]
@rosnk, how is your store created? Is it included in the project? I've created a gist with the code you have, and it worked for me: https://gist.github.com/alexeyraspopov/8596b6fce1aaf060861d53c7e5ed28a3

**Comment by kyldvs** [comment]
Sounds like not a bug or needs more info.
