### ISSUE TITLE
Null Dispatcher

### ISSUE THREAD

**Issue by BethyDiakabananas** [facebook/flux#371]
Hi all,

I'm working on a React.js app using Coffeescript. When trying to deploy my project with gulp, I keep receiving this error:

`Uncaught Invariant Violation: expected "dispatcher" to be a "Flux.Dispatcher" but got "null"`

This is how I've initialized my dispatcher in my cjsx file:

`dispatcher = new Flux.Dispatcher();
`

What would be the best way to go about this? Thank you in advance for your help

I'll attach the file that contains the dispatcher
[LineStore.zip](https://github.com/facebook/flux/files/416221/LineStore.zip)

**Comment by alexeyraspopov** [comment]
The exception is coming from [here](https://github.com/HubSpot/general-store/blob/master/src/dependencies/StoreDependencyMixin.js#L39-L48). Can you show how do you use `StoreDependencyMixin`?

**Comment by BethyDiakabananas** [comment]
Sure thing. Here's how it's used in this snippet:
`Lines = React.createClass
  mixins: [
    GeneralStore.StoreDependencyMixin(
      lines:
        stores: [LineStore]
        deref: (props, state) =>
          LineStore.get()
    )
  ]`

I've also attached the full source code for context. 
[Lines.zip](https://github.com/facebook/flux/files/416574/Lines.zip)

**Comment by alexeyraspopov** [comment]
Sorry, completely missed another file in the zip.

So, `StoreDependencyMixin` requires second argument to be the dispatcher. Simply pass it in the code you have.

**Comment by BethyDiakabananas** [comment]
Sounds good, thank you!
