### ISSUE TITLE
Fullscreen video artificating during cursor hiding

### ISSUE THREAD

**Issue by teddy-error** [facebook/flux#378]
On MacOS Sierra 10.12 when fullscreen videos (Netflix, Youtube, ...) are playing in Safari while Flux is enabled, light colors in the video will artifact creating a distracting distortion. It is worth noting that this only occurs once the cursor has been hidden by the browser; once the mouse is moved the video distortion ceases. When the color setting is lowered near candle the distortion increases in severity, and the inverse is also true.

**Comment by alexeyraspopov** [comment]
Did you mean [f.lux](https://justgetflux.com/)? This project is JavaScript library which is a bit different thing.

**Comment by teddy-error** [comment]
Oops!
