### ISSUE TITLE
v3.0.0 - Build issue when React isn't installed

### ISSUE THREAD

**Issue by colinkahn** [facebook/flux#380]
I'm upgrading from v2.1.1 and am getting the following error in WebPack:

![screen shot 2016-10-05 at 2 13 19 pm](https://cloud.githubusercontent.com/assets/1444385/19132027/a3131830-8b06-11e6-93bf-e447109fc67d.png)

From the library I'm not directly importing FluxContainer, but I am using Store.

**Comment by kyldvs** [comment]
Yeah any usage of flux/utils will require react to be installed unfortunately, it's listed in the peer dependencies.

https://github.com/facebook/flux/blob/master/package.json#L67

**Comment by colinkahn** [comment]
Could that dependency be isolated to another import? Such as `flux/react`? I think people already are biased to think flux is only for React, making this library have a dependency on it would seem to  only reinforce that perception.

**Comment by alexeyraspopov** [comment]
`FluxContainer` initially implemented for React usage only. If you use Flux with different UI layer, you need different container implementation. Anything else can be imported from `flux/lib/*` which won't require React to be installed.

**Comment by kyldvs** [comment]
I don't think that is a good use of time. Any decent packager should not include the source code for react if you are not using it. If you don't use FluxContainer and your packager still includes react in your bundle I'd consider that a bug in the packager.

**Comment by colinkahn** [comment]
@alexeyraspopov thanks for the tip, lets me keep using Flux without installing a React dependency I won't be making use of.

**Comment by zpao** [comment]
> Any decent packager

FWIW *most* packagers won't/can't do tree shaking yet. While it's great to say it's a bug in the packager, it's not really fair.

> Anything else can be imported from `flux/lib/*`

That'll work but it's not supported so it might break in the future.

We probably should support this is some more official way, maybe make `require('flux/utils/store')` work

**Comment by kyldvs** [comment]
> FWIW most packagers won't/can't do tree shaking yet. While it's great to say it's a bug in the packager, it's not really fair.

That's surprising to me, for some reason I thought webpack did this already.

**Comment by alexeyraspopov** [comment]
> That's surprising to me, for some reason I thought webpack did this already.

It probably will be a part of 2.0, but I'm not sure how this can work (or even possible) with CommonJS Modules.
