### ISSUE TITLE
Missing v3.0.0 on GitHub

### ISSUE THREAD

**Issue by PeterDaveHello** [facebook/flux#381]
Hi there,

I just found that the v3.0.0 was published on npm but not on GitHub, I guess you may forget it, so just report to let you know! Thanks for your working on flux!

cc cdnjs/cdnjs#9301

**Comment by kyldvs** [comment]
Thanks, I just pushed the tag, I think this should resolve the issue: https://github.com/facebook/flux/tree/3.0.0

Let me know if you meant something different!

**Comment by PeterDaveHello** [comment]
@kyldvs thanks!
