### ISSUE TITLE
How to make a api call waitFor a action to finish?

### ISSUE THREAD

**Issue by Jeffwhen** [facebook/flux#384]
I have this `store` updates from server. I would like to put the API call in action creator like that chat room example, except when I realize that way it's not likely possible to `waitFor` other actions.

~~Later I came up with this solution but I am wondering if it adheres the flux pattern. Suppose the API action is A, and B is the action it should wait for. I decided to put a status flag in B's store, and let B emit a event if complete. So in A creator can query B's status first, then decide to proceed or wait for that signal from B.~~

**Comment by alexeyraspopov** [comment]
Action B can return a Promise which action A will handle:

```javascript
async function setOfActions() {
  const result = await B();
  A(...);
}
```

**Comment by Jeffwhen** [comment]
@alexeyraspopov Actually i am doing something like that. What brothering mr is that is it ok for compoments to handle the promises returned from actions. Those Flux docs keep emphasize the idea that data should flow unidirectionally.

**Comment by kyldvs** [comment]
You can find one way of dealing with async actions here: https://github.com/facebook/flux/tree/master/examples
