### ISSUE TITLE
Somebody know work flux with rails?

### ISSUE THREAD

**Issue by marcosvicente** [facebook/flux#391]

**Comment by kyldvs** [comment]
I'm not sure what this means. Try reading through the tutorials and if that doesn't help feel free to post a clear question with more context and information.

**Comment by marcosvicente** [comment]
I have a project with react, and I am using this gem (
https://github.com/reactjs/react-rails), I like to know if exists the gem
for flux. Thanks

2017-01-20 17:32 GMT-02:00 Kyle Davis <notifications@github.com>:

**Comment by kyldvs** [comment]
Not that I'm aware of
