### ISSUE TITLE
Readme example tutorial todomvc incomplete

### ISSUE THREAD

**Issue by dfpena** [facebook/flux#396]
The Readme for the example todomvc misses the import of critical files. That is following the directions exactly does not produce a working todomvc.

**Comment by kyldvs** [comment]
Can you clarify what you mean? If you have errors what are they? If you had to perform additional steps to get a working todomvc what are they?

As far as I'm aware following the steps results in a working todomvc.

**Comment by dfpena** [comment]
Thanks for all the work it took to make this example and once running it was very helpful walk-through. 
There are a few spots that need more explicit clarification. 
I'll just go through them:
> cp -R examples/flux-shell examples/my-todomvc
> cd examples/my-todomvc
> npm install
> npm run watch
> Open examples/my-todomvc/index.html in your browser.
> 
>  You should see a blank page that says "Hello World!"
> 2. Set up TodoMVC assets
> 
> Copy assets from examples/todomvc-common
> 
> cp -R ../todomvc-common todomvc-common
> 

It isn't clear given that the original open terminal in examples/my-todomvc is now running npm run watch,  where you are copying files to. The reader (hopefully) reasonably guesses my-todomvc. 

> Now we can use this structure, along with a simple Counter to implement the ADD_TODO action. Update data/TodoStore.js.
> 
> class TodoStore extends ReduceStore {

Should include an import statement for Counter and Todo and just a general point here... at some points in this readme... the author tells the reader to update a file and lists the entire contents of the file to replace, but here and other spots the reader should only update a specific function (reduce). Coincidentally...  the definition of update is mutable... leading to confusion... or is that ironic or both? I would just stick to listing the entire contents of the file.
