### ISSUE TITLE
Subclasses problem

### ISSUE THREAD

**Issue by Kcin1993** [facebook/flux#399]
I following the [example](https://github.com/facebook/flux/tree/master/examples/flux-todomvc) after finishing the step of _3. Setting up Flux_ . My local file doesn't show "Hello from Flux!"

Here is the error in console:
`Uncaught Error: Subclasses of FluxReduceStore must override getInitialState() with their own implementation.`

Anyone meets this problem?

**Comment by kyldvs** [comment]
The contents of your repository when experiencing this error would be helpful to see

**Comment by kyldvs** [comment]
Please re-open with more info if you still have this issue.
