### ISSUE TITLE
Bring back FluxMapStore in a separate npm package for immutable stuff

### ISSUE THREAD

**Issue by Daniel15** [facebook/flux#407]
@kad, what do you think? People using the regular Flux package won't get the immutable-js dependency, but people that do want to use it could add a separate npm package (say `flux-immutable` or something similar).

**Comment by alexeyraspopov** [comment]
`npm install immutable` is just enough to start using needed functionality. What's the advantages of having one more package when Flux works with immutable structures by default?

**Comment by Daniel15** [comment]
@alexeyraspopov  - The `FluxMapStore` is useful as it removes some of the boilerplate around dealing with maps. Internally at Facebook we have a store that extends `FluxMapStore` to handle "load objects" (objects that contain a value as well as a loading state) and it's one of our more commonly-used store base classes.

**Comment by yangshun** [comment]
I'll close this since Flux is in maintenance mode for the foreseeable future.
