### ISSUE TITLE
Flux utils : How to passing props from Container to Container ???

### ISSUE THREAD

**Issue by longtk** [facebook/flux#409]
I call an Container inside an Container , but confuse that how to passing props from Container A to Container B , I had read about 

> containers cannot access props By default containers are not able to access any props. This is both for performance reasons, and to ensure that containers are re-usable and props do not have to be threaded throughout a component tree. There are some valid situations in which you need to determine your state based on both props and a store's state. In those situations pass options {withProps: true} as the second argument to create(). This will expose the components props as the second argument to calculateState().

And try to research but cannot find any solution . 

```
class ActivityLayout extends React.Component {
render() {
       
            var popup = this.state.isShowPopup ?   <PopupContainer tooglePopup={this.tooglePopup}  />:<div></div>;
            var acFormStyle = this.state.isShowPopup ? "none":"block";
            return 
                    <div> {popup}</div>;
        

    }
}
export default ActivityListView;
```
And here is my PopupContainer : 

```
function getStores(){
    return [PhotoStore];
}
function calculateState(prevState,props) {
        console.log(props.tooglePopup);
        return {
           //tooglePopup: PhotoStore.get(props.tooglePopup),
           tooglePopup: props.tooglePopup(),
        };
    }
function getState(){
    return {
        photos:PhotoStore.getState(),
    };
}

export default Container.createFunctional(PopupView, getStores, getState ,calculateState , { withProps: true } );

```

**Comment by kyldvs** [comment]
Container.createFunctional only accepts 4 arguments, you gave it 5

**Comment by KetrinJohnson01110101** [comment]
OK! How to test your code on jest?)

**Comment by kyldvs** [comment]
https://github.com/facebook/flux/blob/master/examples/README.md

https://github.com/facebook/flux/tree/master/examples/flux-jest
