### ISSUE TITLE
Flux dispatcher example uses property not found in Store API

### ISSUE THREAD

**Issue by singhshashi** [facebook/flux#410]
Please refer to the example in the comments at [https://github.com/facebook/flux/blob/master/src/Dispatcher.js](https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L83)

Here to get the dispatchToken from the Store, Store.dispatchToken is used. Whereas as per the Store API documentation, the method to get the dispatchToken is [getDispatchToken](https://facebook.github.io/flux/docs/flux-utils.html#store)

Raising a PR to fix this.

**Comment by kyldvs** [comment]
Thanks for pointing this out, but it is not technically incorrect :)

The dispatcher doesn't have to be used with FluxStore. Right now the documentation assigns the token to the store's `.dispatchToken` property and accesses it in that way consistently throughout:

https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L69

I don't think this needs to be updated.
