### ISSUE TITLE
 Does flux/utils/Container.createFunctional work with 'react-router@v3?

### ISSUE THREAD

**Issue by km-tr** [facebook/flux#413]
- `props.router` is not passed to` StatelessFuncApp`
```
export default withRouter(Container.createFunctional(
  StatelessFuncApp,
  () => [Store],
  () => ({conditions: Store.getState()}),
))
```

- Become an error
```
export default Container.createFunctional(
  withRouter(StatelessFuncApp),
  () => [Store],
  () => ({conditions: Store.getState()}),
)
```

```
Warning: Something is calling a React component directly. Use a factory or JSX instead. See: https://fb.me/react-legacyfactory

Uncaught TypeError: Cannot read property '__reactAutoBindPairs' of undefined
```

Why does `Container.createFunctional` not take components from class as arguments?

**Comment by km-tr** [comment]
I reread the source code and solved it. It worked out successfully below.
```
export default withRouter(Container.createFunctional(
  StatelessFuncApp,
  () => [Store],
  (prevState, props) => ({...props, conditions: Store.getState()}),
  {withProps: true}
))
```

> Why does Container.createFunctional not take components from class as arguments?
Just mentioned above.

**Comment by kyldvs** [comment]
When it was written there was some problems with functional components which forced us to literally call the function rather than create it properly with JSX syntax, I think at this point it could be fixed by updating this line to use JSX: https://github.com/facebook/flux/blob/master/src/container/FluxContainer.js#L266

**Comment by km-tr** [comment]
I saw the code to try jsx, but can not I raise the babel version from 5?
