### ISSUE TITLE
ERROR in ./~/flux/index.js

### ISSUE THREAD

**Issue by Robust1308** [facebook/flux#415]
Hello, I'm new to flux and I have followed to step: 3. Setting up Flux

But after fill all sample codes, I ran into an error:

```
ERROR in ./~/flux/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Dispatcher in /home/tdquang/Workshop/flux/examples/my-todomvc/node_modules/flux
 @ ./~/flux/index.js 10:28-55
```

What did I do wrong???

Many thanks!!!

**Comment by kyldvs** [comment]
Does running `npm run build` fix the issue?

**Comment by Robust1308** [comment]
I got the same error on running `npm run build`

**Comment by kyldvs** [comment]
This seems like you just are running something from the wrong directory/your setup is incorrect.

Can you follow the steps exactly here: https://github.com/facebook/flux/tree/master/examples/flux-todomvc#1-getting-started

And let me know which step fails? When it does fail what is the entire output? And what is the entire output of `pwd` and `ls -asl`?
