### ISSUE TITLE
Sync website with github again

### ISSUE THREAD

**Issue by shogunsea** [facebook/flux#418]
https://facebook.github.io/flux/docs/flux-utils.html

```
There are four main classes exposed in Flux Utils:
```
On github it says `three` but on production page it still says `four`

**Comment by kyldvs** [comment]
Yeah it's really annoying to do a website release :( the scripts are like 4 years old, will leave this up to track doing another release. If `four` -> `three` is the only change I don't think it will be very high pri to me though

**Comment by shogunsea** [comment]
@kyldvs thanks for the info, I agree it's low priority. glad it is being tracked now.

**Comment by yangshun** [comment]
This has been fixed - https://facebook.github.io/flux/docs/flux-utils/
