### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by mikecousins** [facebook/flux#419]
Currently this doesn't work with React 16 beta. What is the timeline looking like for supporting React 16?

**Comment by kyldvs** [comment]
Can you elaborate on what does not work? And I can look into fixing it

**Comment by mikecousins** [comment]
It might be as simple as changing your peerDependencies:

```"peerDependencies": {
    "react": "^15.0.2"
  },```

That could change to `^15.0.2 || ^16.0.0` or `>=15.0.2`

**Comment by mikecousins** [comment]
Created a pull request for this. #420

**Comment by kyldvs** [comment]
Ah, just to more clearly state the problem, this is necessary because the `^` only allows higher minor versions so if you have React 16 as a dependency the Flux package would not believe dependencies are satisfied since it needs a version of 15.

**Comment by mikecousins** [comment]
Yes, exactly.

**Comment by mikecousins** [comment]
Any idea when the next release of Flux might go out?

**Comment by kyldvs** [comment]
@mikecousins Just published https://github.com/facebook/flux/tree/3.1.3
