### ISSUE TITLE
flux-jest: npm run test fails

### ISSUE THREAD

**Issue by thaijaso** [facebook/flux#422]
$ npm run test
openssl config failed: error:02001003:system library:fopen:No such process

> flux-jest@1.0.0 test C:\Users\JThai3\workspace\flux\examples\flux-jest
> jest

 FAIL  src\__tests__\TodoStore-test.js
  ● Test suite failed to run

    ReferenceError: Unknown plugin "syntax-async-functions" specified in "C:\\Users\\JThai3\\workspace\\flux\\examples\\flux-todomvc\\.babelrc" at 0, attempted to resolve relative to "C:\\Users\\JThai3\\workspace\\flux\\examples\\flux-todomvc"

      at node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
      at Array.map (native)

Test Summary
 › Ran all tests.
 › 1 test suite failed, 0 tests passed (0 total in 1 test suite, run time 1.162s)
openssl config failed: error:02001003:system library:fopen:No such process

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! flux-jest@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flux-jest@1.0.0 test script 'jest'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the flux-jest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs flux-jest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls flux-jest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JThai3\workspace\flux\examples\flux-jest\npm-debug.log
openssl config failed: error:02001003:system library:fopen:No such process

**Comment by myshov** [comment]
I think this issue somewhat related to this issue in npm https://github.com/npm/npm/issues/17261

Try to remove environment variable in the cmd.exe (or what you use) via this command:
```
set OPENSSL_CONF=
```
and check if it will help. If so this issue can be closed.

**Comment by kolasss** [comment]
I have almost the same error
```
$nodejs -v
v8.5.0
$npm -v
5.4.2
```
```
$ npm run test

> flux-jest@1.0.0 test /home/kolas/projects/nodejs/flux/examples/flux-jest
> jest

 FAIL  src/__tests__/TodoStore-test.js
  ● Test suite failed to run

    ReferenceError: Unknown plugin "syntax-async-functions" specified in "/home/kolas/projects/nodejs/flux/examples/flux-todomvc/.babelrc" at 0, attempted to resolve relative to "/home/kolas/projects/nodejs/flux/examples/flux-todomvc"
      
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
          at Array.map (<anonymous>)

Test Summary
 › Ran all tests.
 › 1 test suite failed, 0 tests passed (0 total in 1 test suite, run time 0.647s)
```

**Comment by champagne-randy** [comment]
thanks for the tip @kolasss. This solved the problem for me as well +1
