### ISSUE TITLE
What's the difference of redux an flux?

### ISSUE THREAD

**Issue by yanlee26** [facebook/flux#435]

**Comment by kyldvs** [comment]
Flux is a way of thinking about state management, Redux implements some utilities to help follow a flux-like pattern http://redux.js.org/

**Comment by yanmagale** [comment]
@yanlee26 good question. It's a frequently question that we received at community when some try study Redux or Flux. 

Flux is an architecture pattern, just like MVC and so many others. Its a concept.

Redux, Fluxxor, Vuex, CerebralJS and so many others state management library that turns possible works with state management in your applications, and all are based at Flux concept. Each one works with different way, only using helpers, function programming and others.

I created a list to share resources and contents about this. Check this out - https://github.com/yanmagale/awesome-flux

**Comment by janat08** [comment]
Flux utils is flux therefore not a concept. I think it should be explained that flux untils aren't much of lightweight redux, and as such just link redux guide after the fact, in readme.
