### ISSUE TITLE
[Dispatcher] How is it possible dispatch function to be exectuted simultaneously

### ISSUE THREAD

**Issue by BamaBoy** [facebook/flux#436]
I've checked out the code of `Dispatcher` dispatch function.
```
dispatch(payload: TPayload): void {
    invariant(
      !this._isDispatching,
      'Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.'
    );
    this._startDispatching(payload);
    try {
      for (var id in this._callbacks) {
        if (this._isPending[id]) {
          continue;
        }
        this._invokeCallback(id);
      }
    } finally {
      this._stopDispatching();
    }
  }
```
`_startDispatching` sets `_isDispatching` to **true**.
`_stopDispatching` sets `_isDispatching` to **false**.
Since we check out `isDispatching` props this means, that we can call `dispatch` function, during it's execution.
The code of this function is **synchronous**. So, how is it possible to call `dispatch` function while execution?

**Comment by kyldvs** [comment]
It prevents dispatching in the middle of another dispatch, in particular this test: https://github.com/facebook/flux/blob/master/src/__tests__/Dispatcher-test.js#L85-L94

**Comment by BamaBoy** [comment]
@kyldvs Thank's a lot!
