### ISSUE TITLE
Switch from BSD + Patents to MIT license

### ISSUE THREAD

**Issue by RafalCichon** [facebook/flux#439]
It would be great to get flux with MIT license, just like react, since the current license (BSD + Patents) is quite a problem for many people.

**Comment by kyldvs** [comment]
I probably will not put much effort into this unless it becomes a larger issue. Flux is more of a pattern anyway and this particular implementation is not all that important. There are many popular alternatives under the MIT license: https://github.com/reactjs/redux/blob/master/LICENSE.md

**Comment by sandipp** [comment]
Flux is used by one package we are intended to use but cause of `Flux` License it's not allowed for us to use. So please consider reopening this issue and updating License to MIT License.
Thanks.
