### ISSUE TITLE
seems library are missing when install npm

### ISSUE THREAD

**Issue by Jorgininho** [facebook/flux#441]
hello, I followed your tutorial on flux on the todo list.
at step "3. Setting up Flux" when I modify the root.js, i get the following issue : 

> ERROR in /home/jubo/infini-fab/web/test/flux/utils.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/FluxContainer in /home/jubo/infini-fab/web/test/flux
>  @ /home/jubo/infini-fab/web/test/flux/utils.js 10:27-57
> 
> ERROR in /home/jubo/infini-fab/web/test/flux/utils.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/FluxMixinLegacy in /home/jubo/infini-fab/web/test/flux
>  @ /home/jubo/infini-fab/web/test/flux/utils.js 11:23-55
> 
> ERROR in /home/jubo/infini-fab/web/test/flux/utils.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/FluxReduceStore in /home/jubo/infini-fab/web/test/flux
>  @ /home/jubo/infini-fab/web/test/flux/utils.js 12:29-61
> 
> ERROR in /home/jubo/infini-fab/web/test/flux/utils.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/FluxStore in /home/jubo/infini-fab/web/test/flux
>  @ /home/jubo/infini-fab/web/test/flux/utils.js 13:23-49
> 
> ERROR in /home/jubo/infini-fab/web/test/flux/index.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/Dispatcher in /home/jubo/infini-fab/web/test/flux
>  @ /home/jubo/infini-fab/web/test/flux/index.js 10:28-55

there no folder "lib" created during the install. Here are the warning I have during the npm install : 

> npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
> npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
> npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
> npm WARN lifecycle flux@3.1.3~prepublish: cannot run in wd %s %s (wd=%s) flux@3.1.3 gulp publish /home/jubo/infini-fab/web/test/flux
> npm WARN babelify@8.0.0 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> added 116 packages in 14.406s

My OS : Ubuntu 16.04
node : v 8.9.1
npm : v 5.5.1

Thanks

**Comment by hopeseekr** [comment]
I'm having this exact same problem!

**Comment by hopeseekr** [comment]
Here's my fix for this issue: 

https://stackoverflow.com/a/47427544/430062

**Comment by evergreen2001** [comment]
ok
