### ISSUE TITLE
React 16.x support (TypeScript)

### ISSUE THREAD

**Issue by ruslanchek** [facebook/flux#442]
I getting lots of these errors:
`ERROR in [at-loader] ./node_modules/@types/flux/node_modules/@types/react/index.d.ts:2762:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'HTMLProps<HTMLAnchorElement>'.`

**Comment by yangshun** [comment]
We support React 17+ in flux@4.0.0 now, this should be irrelevant.
