### ISSUE TITLE
Per app settings - feature request

### ISSUE THREAD

**Issue by michaelfresco** [facebook/flux#444]
At night, I like to all my apps to be in 'dark mode'. So, I installed the Google Chrome Haddon 'Dark reader' but unfortunately it slows down the browsing experience in a really bad way. So, I was thinking, I should really get a 'filter for Google Chrome'.

I was hoping that future versions of Flux maybe could include a per app setting. I like it when my Apple system looks 90% normal, but some apps are in dark mode.

Ideally, you'd also get a smart color invert, like Apple introduced on the latest versions of iOS.

**Comment by kyldvs** [comment]
I think you are trying to request a feature for f.lux (https://justgetflux.com/), that's not what this repository is. This is a JavaScript framework, not any sort of application.

**Comment by wh0am123** [comment]
Thanks!

2017-12-20 0:57 GMT+01:00 Kyle Davis <notifications@github.com>:

**Comment by wh0am123** [comment]
Hey,Do you need a programmer?

2017-12-20 21:37 GMT+01:00 the jyj Co. <thejyjco@gmail.com>:
