### ISSUE TITLE
npm error missing script watch is coming

### ISSUE THREAD

**Issue by flik** [facebook/flux#445]
H:\books\js\flux>npm run watch
npm ERR! missing script: watch

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jan2018\AppData\Roaming\npm-cache\_logs\2018-02-07T03_08_2

**Comment by kyldvs** [comment]
`watch` is not a valid command: https://github.com/facebook/flux/blob/master/package.json#L23-L27

What would you expect it to do?

**Comment by flik** [comment]
I was following instructions on https://github.com/facebook/flux/tree/master/examples/flux-todomvc
and want expected results.

**Comment by kyldvs** [comment]
You probably forgot this line:

```
cd examples/my-todomvc
```

The main flux directory does not have a watch command, the examples do.

Let me know if that does not fix it.
