### ISSUE TITLE
error with flux when using app [created with create-react-app]

### ISSUE THREAD

**Issue by pjannik** [facebook/flux#446]
when dev server starts up I get following error in browser [chrome]
TypeError: __WEBPACK_IMPORTED_MODULE_0_flux_utils___default.a.createFunctional is not a function

![capture](https://user-images.githubusercontent.com/36763259/36593349-920b031e-1899-11e8-9b90-3599ee8a376e.PNG)

**Comment by kyldvs** [comment]
Probably has to do with your specific setup, the function does exist: https://github.com/facebook/flux/blob/master/src/container/FluxContainer.js#L245-L250

Are you on an old version of Flux or are you forgetting to import container? If this is the default setup of create-react-app it might be worth filing an issue with them.

**Comment by pjannik** [comment]
Latest version of flux, container imported and also default setup [create-react-app].
I will try and file the issue with create-react-app.

**Comment by pjannik** [comment]
You were right about import, I had forgotten {} around "import {Container} from ...."
