### ISSUE TITLE
Unable to launch todo example app

### ISSUE THREAD

**Issue by mjstelly** [facebook/flux#454]
Node: v9.11.1
Npm: 5.6.0
flux: 3.1.3
I followed the steps described in the `flux-todomvc`, first installing with `yarn` then `npm`. Upon attempting to launch, I got the console output

>npm run watch
 flux-shell@1.0.0 watch /Users/michaelstelly/Documents/projects/flux/examples/my-todomvc
 webpack ./src/root.js ./bundle.js --watch
Hash: 146a9c664d4f07a79716
Version: webpack 1.15.0
Time: 1521ms
    Asset    Size  Chunks             Chunk Names
bundle.js  746 kB       0  [emitted]  main
    + 184 hidden modules

Running  `examples/my-todomvc/index.html`, all I get is a Google search page. I can't get the example to run. No idea why this isn't working.

**Comment by kyldvs** [comment]
What is the exact URL you are using? For example I would load this URL in my browser:

```
file:///C:/Users/kad/flux/examples/my-todomvc/index.html
```

**Comment by kyldvs** [comment]
I just confirmed that these steps work on my machine:

1. `git clone https://github.com/facebook/flux.git`
2. `cd flux`
3. `npm install`
4. `cd examples/flux-todomvc`
5. `npm install`
6. `npm run build`
7. Load: `file:///C:/Users/kad/dev/flux/examples/flux-todomvc/index.html`

**Comment by mjstelly** [comment]
Just the URL I posted `examples/my-todomvc/index.html`. It didn't say what the access protocol was. Another problem is that Chrome on Mac keeps rewriting my URL. `file://Users/michaelstelly/Documents/projects/flux/examples/my-todomvc/index.html` gets converted to file://users/michaelstelly/Documents/projects/flux/examples/my-todomvc/index.html` (lowercase "users") which screws everything up. Safari did the same thing, reset `Users` to lowercase.

**Comment by kyldvs** [comment]
You can navigate to the `.html` file in finder and should be able to just double click it to open it I believe.

Going to close this, as it's not actually an issue with this repo.

**Comment by kyldvs** [comment]
Mac filesystem is not case-sensitive so rewriting it to lowercase should not matter.

**Comment by mjstelly** [comment]
Sorry to bug you. Didn't think about accessing the index file directly. Been awhile since I worked with html files so I forgot. Thanks for the quick response.

**Comment by kyldvs** [comment]
No problem, If you run into any other issues let us know!
