### ISSUE TITLE
how to combine two store in a common store

### ISSUE THREAD

**Issue by rathorebs** [facebook/flux#457]
I want to call states from two store in component but state didn't update so Please suggests me any solution how to call multiple stores in single component or how to combine stores in common store

**Comment by kyldvs** [comment]
The Flux TodoMVC example has a container using multiple stores, check it out here:

- https://github.com/facebook/flux/tree/master/examples/flux-todomvc
- https://github.com/facebook/flux/blob/master/examples/flux-todomvc/src/containers/AppContainer.js#L21-L23
