### ISSUE TITLE
Questions about behavior Container.createFunctional

### ISSUE THREAD

**Issue by jomarquez21** [facebook/flux#460]
Why should we add many stores? in function getStores
```javascript
function getStores() {
  return [
    TodoStore,
    // TodoDraftStore
  ];
}
```
since it works in the same way, adding an extra store in 
```javascript
function getState() {
  return {
    draft: TodoDraftStore.getState(),
    todos: TodoStore.getState(),

    onAdd: TodoActions.addTodo,
    onDeleteTodo: TodoActions.deleteTodo,
    onToggleTodo: TodoActions.toggleTodo,
    onUpdateDraft: TodoActions.updateDraft,
  };
}
```
I do not understand this behavior is supposed that if it is not added in the `getStore` the store should not work

Can you help me, please?

**Comment by kyldvs** [comment]
The rule is that, if you use a store in `getState()` it *must* be returned from `getStores()`. This is so that when the store emits a change event the container knows that it needs to re-run `getState()` and update the state of the component.
