### ISSUE TITLE
Load initial

### ISSUE THREAD

**Issue by jomarquez21** [facebook/flux#461]
best regards

Can someone help me understand how the initial load in the flux-async example works? I do not understand how the `todo` request is executed after the request of` ids`

thank you very much.

**Comment by kyldvs** [comment]
Hello, thanks for the question!

First you will need to understand how "LoadObjects" work. There is a description here: https://github.com/facebook/flux/tree/master/examples/flux-async#loadobject

Basically, they are in a "loading state" at the start, and when you try to access the data inside of them they will request that data and dispatch an action when the data comes back from the server.

From there you can follow the sequence of events that loads data in the async example:

1. [Render AppContainer](https://github.com/facebook/flux/blob/master/examples/flux-async/src/root.js#L20)
2. [Get IDs from TodoListStore](https://github.com/facebook/flux/blob/master/examples/flux-async/src/containers/AppContainer.js#L33)
    - [Mapping over the LoadObject's data](https://github.com/facebook/flux/blob/master/examples/flux-async/src/containers/AppContainer.js#L47)
    - [Causes a call to getLoadObject()](https://github.com/facebook/flux/blob/master/examples/flux-async/src/load_object/LoadObjectState.js#L64)
    - [Causes a call to the load function](https://github.com/facebook/flux/blob/master/examples/flux-async/src/load_object/LoadObjectState.js#L44)
    - [Causes the TodoListStore to load ids](https://github.com/facebook/flux/blob/master/examples/flux-async/src/stores/TodoListStore.js#L32-L34)
3. [Each id from TodoListStore is then requested from TodoStore](https://github.com/facebook/flux/blob/master/examples/flux-async/src/views/AppView.js#L110)
    - [Which can cause a load](https://github.com/facebook/flux/blob/master/examples/flux-async/src/load_object/LoadObjectMap.js#L66)
    - [Which is defined in TodoStore](https://github.com/facebook/flux/blob/master/examples/flux-async/src/stores/TodoStore.js#L33-L36)

Please let me know if you have more questions!
