### ISSUE TITLE
What benefits can we get from flux?

### ISSUE THREAD

**Issue by rabbitooops** [facebook/flux#463]
`dispatch`: a call of a function
`action.type`: function name
`action.payload`: function's parameters

Example:
`dispatch({type: 'SET_GENDER', payload: 'female'})`
is equivalent to
`setGender('female')`

And `action.type` is not reliable because it's a string.

**Comment by kyldvs** [comment]
The main point of Flux is make data flow in one direction. A setter function allows mutations and two-way data flow. https://github.com/facebook/flux/tree/master/examples/flux-concepts#flow-of-data


There are lots of guides on this topic online it seems, this was the first one I found when searching "should I use Flux": https://blog.andrewray.me/flux-for-stupid-people/
