### ISSUE TITLE
Flux Utils + Hooks

### ISSUE THREAD

**Issue by patelnav** [facebook/flux#468]
This would be a killer feature. We would be able to throw away Containers with all the calculateState/withProps/withContext ugliness. 

Is there anybody working on this? otherwise I could take a pass.

**Comment by patelnav** [comment]
If anybody has an implementation they're using already, would love to see it!

**Comment by patelnav** [comment]
Had to deal with this issue for now, so I've published a package: [flux-hooks](https://www.npmjs.com/package/flux-hooks).

It's a pretty [simple implementation](https://github.com/Fieldscope/flux-hooks/blob/master/index.js) that does the trick, let me know if its makes sense for it to live in this repo.

**Comment by kyldvs** [comment]
I think they work well as an external package for now, we may want to move them in here at some point but I don't think it's a pressing issue. Happy to add a link to them in the docs where you think it makes sense though!

**Comment by patelnav** [comment]
Thanks @kyldvs 

I think if you're using hooks, it makes sense to create a Flux implementation from scratch. It should be fairly minimal. Perhaps Flux Utils can define that simple implementation in the future.  

For now, I needed this because I already have a fairly large project that's using ReduceStore.

Best spot for a link in the docs might be at the bottom of the [Flux Utils page](https://github.com/facebook/flux/blob/master/docs/Flux-Utils.md)?

**Comment by kyldvs** [comment]
Yeah with `useReducer` and `useContext` I feel like you can get most of the benefits of flux using vanilla hooks.

Want to submit a PR with a quick explanation and link in its own "Using Flux with React Hooks" section at the bottom of that page?

**Comment by kyldvs** [comment]
Closing now that docs are updated
