### ISSUE TITLE
Why is it not possible to "dispatch in the middle of a dispatch"

### ISSUE THREAD

**Issue by mosch** [facebook/flux#47]
Is there any reason why the dispatcher can't handle a dispatch in the middle of a dispatch?

I can't be sure, that this will not happen. I have a lot of async API calls that will dispatch events simultaneously and i'm running into this error.

Am i doing s.th. wrong? Is there any reason why you should not have a queue in the dispatcher?

**Comment by achobanov** [comment]
@fisherwebdev Thanks for your reply. Let's imagine I have multiple instances of the same component, which must fire an action inside componentDidMount.  All of those components are rendered from an array of data objects ( simultaneously ). How should I implement this? I am using Alt, but their docs say they use your dispatcher, so I figured I should ask here as well. Thanks
