### ISSUE TITLE
TypeError: Class constructor App cannot be invoked without 'new'

### ISSUE THREAD

**Issue by adiRandom** [facebook/flux#470]
I have the following `App` component that I am trying to turn into a container using Flux Utils:
  
   ```
 class App extends React.Component<{},AppState> {
	constructor(props:Readonly<{}>){
		super(props);	
	}
	static getStores(){
		return [ArticlesStore];
	}

	static calculateState(prevState:AppState):AppState{
		return {
			articles:ArticlesStore.getState()
		}
	}
	render() {
		return (
			<main>
				<Navbar></Navbar>
				<Routes></Routes>
			</main>
		);
	}
}


interface AppState{
	/**
	 * Articles retrived from the ArticlesState to be used in the rendering of the page
	 */
	articles:ArticlesStoreState;
}

export default Container.create(App);
```

When running this code, I am getting this TypeError : `TypeError: Class constructor App cannot be invoked without 'new'`. 

I've checked the provided example on the Flux website, but I can't figure out why this error is being thrown.  Any ideas?

**Comment by kyldvs** [comment]
This appears to be the exact same issue as https://github.com/facebook/create-react-app/issues/1751#issuecomment-284763003, does the discussion there help?
