### ISSUE TITLE
Please update the following components: FluxContainer(containerClass) React 16.10.2

### ISSUE THREAD

**Issue by DonikaV** [facebook/flux#478]
react-dom.development.js:12372 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Please update the following components: FluxContainer(containerClass)**

**Comment by DonikaV** [comment]
somehow react-codemod fixed this :)

**Comment by DonikaV** [comment]
nothing? :(

**Comment by JasonKaz** [comment]
@DonikaV Looks like this got fixed before you made this issue: https://github.com/facebook/flux/commit/466130cd0fd5d74961f28fb0e2b64b87802dbfe0

However there hasn't been a new publish of this package in 3 years, so the latest published version does not have this change.

**Comment by jklimke** [comment]
As a simple install from github is not possible, could you please publish an updated version of the library to npm ?

**Comment by leroix** [comment]
Looks like 4.0.0 was published 8 days ago. Perhaps, this can be closed?

**Comment by yangshun** [comment]
Thanks, closing this.
