### ISSUE TITLE
Any thoughts on switching to webpack with hot-reload

### ISSUE THREAD

**Issue by justin808** [facebook/flux#50]
I've got the React tutorial running with ES6 with Webpack: https://github.com/justin808/react-tutorial-hot/tree/es6.

This seems way better than watchify.

@petehunt turned me to webpack and it's awesome. 

I'd be happy to submit a PR for the two example programs if this is useful.

**Comment by pikeas** [comment]
@fisherwebdev Hot reload (whether via webpack, browsersync.io, or other library) makes exploratory development -- AKA, exactly what an interested React/Flux beginner will want to do -- significantly easier.

**Comment by sterpe** [comment]
@pikeas given the issues cited here (for example) http://mattdesl.svbtle.com/browserify-vs-webpack

Why would webpack be any easier than currently using browserify?  It certainly seems less scalable.

Looking at the documentation for webpack the configuration is almost more complex than require.js-- which feels like a step back, but the killer issue is that the overloading of require calls with loader directives makes webpack modules unrunnable in node:

require('!json!./foo.json')

That's hard to see as a win.

**Comment by pikeas** [comment]
@sterpe Your points are fair. Although I personally prefer webpack, I'm advocating for hot reloading in some capacity, regardless of implementation details.

**Comment by sterpe** [comment]
Sure but there we get into that configuration complexity to do something that browserify does with none or very little.  Just seems weird to me.

Really do we need to hot load these demos?  Honestly how much time do people spend playing with them before they put them away and start building something real?

**Comment by fisherwebdev** [comment]
I'd rather not have the Browserify vs. Webpack debate here.  If you're inclined, there are plenty of other places on the web to have that debate, such as https://gist.github.com/substack/68f8d502be42d5cd4942.

I think a new Flux example might be worth developing -- perhaps that one could use Webpack, just to show another way of doing it.  The subject of a new example has come up a couple of times, most recently in #134, so I think we could see a Webpack example soon.
