### ISSUE TITLE
Is fbemitter project discontinued? Is flux?

### ISSUE THREAD

**Issue by DullReferenceException** [facebook/flux#506]
Is the flux project considered dead? There are some security audit issues that are not addressed. These come from dependencies on `fbemitter`, but the [github repo for `fbemitter`](https://github.com/facebookarchive/emitter) is archived. This means community contributions to fix this via dependency bumps appear to be impossible.

Is `fbemitter` located somewhere else, or are we expected to migrate code bases away from `flux` to alternate implementations like `redux`?

**Comment by yangshun** [comment]
>  This means community contributions to fix this via dependency bumps appear to be impossible.

Yes you're right. The Flux project is in maintenance mode and there are many more sophisticated alternatives available (e.g. Redux, Mobx) and we would recommend using them instead. We'll update the README to reflect this.
