### ISSUE TITLE
NPM reports flux vulnerabilities 

### ISSUE THREAD

**Issue by xero-lib** [facebook/flux#513]
![image](https://user-images.githubusercontent.com/54485853/100783774-d2a3d380-33d3-11eb-84a3-138d478fc887.png)
Thought I'd let y'all know.

**Comment by xero-lib** [comment]
As well as wondering what I might do to fix this, as using audit just removes flux.

**Comment by yangshun** [comment]
Unfortunately many of them lie in [fbjs](https://github.com/facebook/fbjs) and not within Flux. We don't own fbjs but we'll update Flux's fbjs version if/when fbjs gets updated.

**Comment by xero-lib** [comment]
> Unfortunately many of them lie in [fbjs](https://github.com/facebook/fbjs) and not within Flux. We don't own fbjs but we'll update Flux's fbjs version if/when fbjs gets updated.

Alright, thanks for letting me know.
