### ISSUE TITLE
Why _onChange called with line feed in chat example, but not todo example.

### ISSUE THREAD

**Issue by justin808** [facebook/flux#53]
Per this change:
https://github.com/justin808/flux/commit/643ca19b68ec63170648e9f5cba2456aba23a92c

I can't figure out why `_onChange` is not called in the todo example after return is pressed, yet it is called in the chat example.

I'm guessing there must be some subtle difference.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyldvs** [comment]
Pretty old, closing this out. Sounds like there might be a bug in your code :) didn't seem obvious to me right away either.
