### ISSUE TITLE
[Question] store.getItem() which may require an async server call

### ISSUE THREAD

**Issue by abergs** [facebook/flux#60]
Hi. I want to discuss the best practice for a situation where data will be lazily fetched and if the way I'm currently doing it is a good way to do it.

1. view calls `store.getItem(123)`
2. store realize it haven't loaded item 123
3. store sets loading = true
4. store calls `API.LoadItem({id:123})`
5. store emits that it has changed (due to loading = true)
6. store returns null
7. view handles null result
8. view receives change event and can show user that store is loading
9. [Async at 4] API.LoadItem fires ajax request. When request is resolved, fires `Actions.ItemLoaded({result: ...})`
10. store receives callback on ItemLoaded, stores the result, sets loading to false and emit that it has changed.
11. view receives change event, and updates it state, effetively recalling store.getItem(123).

Is this the proper way to solve such problem? I can see one issue above, which is number 6 & 7, because if `getItem` returns null, the view don't know if the resource doesn't exist or if it's pending. Would it be wise to wrap all get-calls with a status wrapper that could tell if we know for sure that 123 doesn't exist (we already tried ajax request and it failed) or if we just have to fire an request before we have the result.

**Comment by simenbrekken** [comment]
I played around a bit with this approach today:

**Store:**

```jsx
var ProductStore = Reflux.createStore({
  init() {
    this.products = {};
  },

  get(id) {
    // Attempt to fetch product from cache
    var product = this.products[id];

    // If no product was found, create a placeholder while we load it
    if (!product) {
      product = this.products[id] = {
        id: id,
        loading: true
      };

      // Fetch the product from our API
      API.get('/products/' + id)
        .then(res => {
          this.products[id] = res.data;
          this.trigger();
        });
    }

    // Return either the actual product or the placeholder
    return product;
  }
});
```

**Component:**

```jsx
var ProductDetailPage = React.createClass({
  getInitialState() {
    return this.getStateFromStores();
  },

  getStateFromStores() {
    var productId = this.getQuery().productId;

    return {
      product: ProductStore.get(productId)
    };
  },

  onStoreChange() {
    this.setState(this.getStateFromStores());
  },

  componentDidMount() {
    this.listenTo(ProductStore, this.onStoreChange);
  },

  render() {
    var product = this.state.product;

    return product.loading ? <Loader /> : <ProductDetails product={product} />;
  }
});
```

I've yet to play around with list type responses yet, but I'm leaning towards wrapping list results in a type of "query"-object that includes the list of data along with `hasMore`, `total` etc. for the given query.

**Comment by jsdw** [comment]
This is really interesting. In my angular apps I tend to work heavily with promises. I essentially hevr stores that maintain a promise based cache of things, and each method makes the relevant API request if necessary to populate the cache. for example:

```
var itemCache = {}

function makeApiRequest(url){
	return new Promise(function(res, err){
		//fetch data from server..
		res(data);
	});
}

function copy(item){
	//deep copy item...
	return angular.copy( item );
}

function getItem(id){
	
	//promise for item in cache? return a copy of it
	if(itemCache[id]) {
		return itemCache[id].then(copy)
	}

	//else, immediately cache promise for item:
	var itemPromise = itemCache[id] = makeApiRequest("url/for/item/"+id);
	return itemPromise;
}

//common usage (we can act on "loading" state easily):

isLoadingData = true;
getItem(12).then(function(item){
	 isLoading = false 
	/* do something with item */ 
})


```
The things I like about this approach are

1. Something using this store doesnt care where the data is coming from. It might take a few seconds or it might be instant, but it's handled the same in either case. No need to keep track of loading state. An interested view can do that very easily if it cares, as above.
2. It's really easy in most cases to ensure that a request for something never happens more than once. The moment there is a promise in the cache, every subsequent request will just be handed that same thing.

However, the downsides are that you end up working with promises throughout the system, which introduces a layer of async handling. Also, I imagine storing promises is a less economical approach in terms of memory.

In practise I haven't found these to be a problem (yet), but I am intrigued to see whether a flux style architecture, which eliminates promises and async code from everything but the web API code, can do it better, so I'll be having a go at it for my next project.

@simenbrekken I like your approach. It makes total sense to me to make the XHR request from inside the store, as the store is the thing that knows what exactly it needs to get, and in my mind is responsible for, well, storing whatever data is asked for. Knowing exactly what data it is storing might allow it to be cleverer with regard to making XHR requests as well (eg batching multiple requests for different item details).

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by igo88** [comment]
Is there any update on this issue?

**Comment by kyldvs** [comment]
@igo88 This is one approach that we use quite heavily at Facebook: https://github.com/staltz/flux-challenge/tree/master/submissions/kyldvs

Relevant files are SithStore and SithDataManager.

**Comment by kyldvs** [comment]
Going to close this out since I feel like the example above demonstrates solutions to most aspects of async data in flux. If you would still like to discuss this issue further please feel free to re-open!
