### ISSUE TITLE
[Question] Form Wizard

### ISSUE THREAD

**Issue by mtsyganov** [facebook/flux#64]
I would like to discuss best practice about form wizard.
Following example. We have a page with 3 components: header, content, footer. In the header we show the name of the step. Content component shows the form for actual step. The footer contains buttons to go to the previous step or to the next step.
## Problem 1:

Because the submit button and the form are capsulated in different components, how can we retrieve the data from the form component and submit this data to the server? By clicking on the button in the footer component it fires an action. This action can't contain the form data, because it can't access other components data. The action is received by a store. But the store don't have the form data to send it to server.
### Solution 1.

On every input chage in the form, we fire an action with this change and transfer changed input value to the store. So we can guarantee, that the store always has fresh data of the form.
When the store receives the submit action, it sends its data to server.
Disadvantage is that we have to fire on each keypress an action.
### Solution 2.

In addition to change event we create in the store a request event. Our form listen to the request event. After receiving a submit action the store emit a request event. The form receives the request event, collects all field data and fire an action with collected data to the store.
## Problem 2:

For each step and each form we have different stores. The main process state is handeled by separeted MainStore. MainStore may show a popup with error message. 
For example we have 2 forms on one page. Each form have to be validated by server. After we click on submit button each form store receives the submit action and makes an ajax request to validate its form data. If something with data is wrong the MainStore have to show the error messages in the popup. How to synchronize responses from these two async server validations and show the merged response in the popup by the MainStore?
### Solution 1.

Centralize all validation actions from all forms in the MainStore. The MainStore executes the ajax requests through a promise lib and after complete of all requests it fires a change event with merged server response. In this solution the MainStore should have write access to other stores to transfert the server field errors to form stores. 
Disadvantage is that we have a very big MainStore with whole logic.
### Solution 2.

Submit action goes to each form store and each form store makes an ajax request to validate its data.  After the form store have received the response from server it has to send the errors to the MainStore, so the MainStore can show the popup with errors. 
Disadvantage is that we have to synchronize all ajax responses from to know when to switch to next step in the wizard.
Other disadvantage is that we cant make a logic in sequences of validations. For example execute form A and if (and only if) the validation is OK execute the validation of form B.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
