### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by totty90** [facebook/flux#71]
You might include this example: https://github.com/totty90/jogabo-flux-react

**Comment by ChuckJHardy** [comment]
Both of the above are missing tests.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by kyldvs** [comment]
We've added another example since this was opened (still todo-mvc) I'm also thinking about potentially pulling in the implementation for: https://github.com/staltz/flux-challenge/tree/master/submissions/kyldvs
