### ISSUE TITLE
Improve "Cannot dispatch in the middle of a dispatch" error with information on actions

### ISSUE THREAD

**Issue by nicolashery** [facebook/flux#95]
This error is useful to spot cascading actions, but it can sometimes be difficult to track down the cause.

Adding information on the `_pendingPayload` as well as the `payload` that triggered the error could be useful. (@iirvine 's Dispatcher has a nice warning message in this spirit: https://github.com/iirvine/fluent-flux/blob/master/src/Dispatcher.js).

How to display each payload? One idea could be having a `_displayAction` method that you could override when constructing the Dispatcher? Something like:

``` javascript
constructor(options) {
  if (options && options.displayAction) {
    this._displayAction = options.displayAction;
  }  
}

_displayAction(payload) {
  return payload.type;
}

dispatch(payload) {
    invariant(
      !this._isDispatching,
      'Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch. ' +
      `Received action '${this._displayAction(payload)}' while still dispatching action '${this._displayAction(this._pendingPayload)}'. `
    );
}
```

I can try to put together a PR for this, but wanted to jot down some ideas here first see what you think...

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
